#!/usr/bin/env node
//
// Read every data/news/<campus>.json and emit src/data/news.generated.ts —
// a single sorted-by-publishedAt list the React app imports at build time.
// Mirrors scripts/crawl/build-data.ts for the program catalog.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { stripHtml } from "./rss.ts";
import type { NewsItem } from "../../../src/data/news.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..", "..");
const NEWS_DIR = join(ROOT, "data", "news");
const OUT = join(ROOT, "src", "data", "news.generated.ts");

interface NewsCrawlFile {
  campus: string;
  items?: NewsItem[];
}

// Resolve a possibly site-relative image URL against its source site's root.
// Feeds like UC San Francisco emit Drupal asset paths such as
// "sites/innovation.ucsf.edu/themes/.../social-default.jpg" — root-relative but
// shipped without a leading slash. The UI drops imageUrl straight into a CSS
// url(), so a relative path would otherwise resolve against our own origin and
// 404. Resolve against the source origin (not the article path, which would
// yield a bogus ".../media/news/sites/…") and drop anything that won't parse.
function absoluteImageUrl(imageUrl: string | undefined, sourceUrl: string): string | undefined {
  if (!imageUrl) return undefined;
  try {
    const resolved = new URL(imageUrl, new URL(sourceUrl).origin);
    // Only ship http(s) images — the value lands in a CSS url(), so keep
    // odd schemes (data:, javascript:, file:, …) out even if a feed emits one.
    if (resolved.protocol !== "http:" && resolved.protocol !== "https:") return undefined;
    return resolved.href;
  } catch {
    return undefined;
  }
}

async function loadAll(): Promise<NewsItem[]> {
  if (!existsSync(NEWS_DIR)) return [];
  const files = (await readdir(NEWS_DIR)).filter((f) => f.endsWith(".json"));
  const all: NewsItem[] = [];
  for (const file of files) {
    const raw = JSON.parse(await readFile(join(NEWS_DIR, file), "utf-8")) as NewsCrawlFile;
    // Normalize display text from every source here. The RSS path already
    // cleans via stripHtml, but the Playwright path stores og:description
    // verbatim, which can carry (double-)encoded entities like "Q&amp;A".
    // Cleaning at the single build step keeps the consumed feed tidy
    // regardless of crawler, now and on future weekly runs.
    for (const item of raw.items ?? []) {
      all.push({
        ...item,
        title: stripHtml(item.title),
        summary: stripHtml(item.summary),
        imageUrl: absoluteImageUrl(item.imageUrl, item.sourceUrl),
      });
    }
  }
  return all;
}

const items = await loadAll();

// Dedupe by id (campus-prefixed). Sort newest first so the UI can
// `slice(0, n)` to render the most recent without re-sorting.
const seen = new Map<string, NewsItem>();
for (const item of items) {
  if (!seen.has(item.id)) seen.set(item.id, item);
}
const sorted = [...seen.values()].toSorted((a, b) =>
  (b.publishedAt || "").localeCompare(a.publishedAt || ""),
);

const generatedAt = new Date().toISOString();

const banner = `// AUTO-GENERATED by \`vp run build-news-data\`. Do not edit by hand.
// Source: data/news/*.json — last refresh: ${generatedAt}
// Run \`vp run crawl:news\` followed by \`vp run build-news-data\` to refresh.`;

const body = `import type { NewsItem } from "./news.ts";

export const NEWS: NewsItem[] = ${JSON.stringify(sorted, null, 2)};
`;

await writeFile(OUT, `${banner}\n${body}`);

console.log(`Wrote ${sorted.length} news item(s) → ${OUT}`);
