#!/usr/bin/env node
//
// Read every data/crawled/<campus>.json file produced by run.mjs, normalize
// the candidates, dedupe by slug across campuses, and emit a single typed
// TypeScript module the React app imports at build time:
//
//   src/data/programs.generated.ts
//
// The UI's `mergePrograms` helper (src/data/normalize.ts) reconciles the
// generated list with the curated PROGRAMS array — curated wins on conflict.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { canonicalIndustries, canonicalStage, canonicalType, slugify } from "./normalize.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");
const CRAWLED_DIR = join(ROOT, "data", "crawled");
const OUT = join(ROOT, "src", "data", "programs.generated.ts");

const FALLBACKS = {
  duration: "Not specified",
  funding: "Not disclosed",
  selectivity: "Not disclosed",
  deadline: "See program site",
  desc: "Program details not yet aggregated. Visit the source page for full information.",
};

function coerce(candidate) {
  const slug = candidate.slug ?? candidate.id ?? slugify(candidate.name);
  return {
    id: candidate.id ?? slug,
    slug,
    name: candidate.name.trim(),
    campus: candidate.campus,
    type: canonicalType(candidate.type),
    desc: candidate.desc?.trim() || FALLBACKS.desc,
    longDescription: candidate.longDescription?.trim() || undefined,
    industries: canonicalIndustries(candidate.industries ?? []),
    stage: canonicalStage(candidate.stage),
    eligibility:
      Array.isArray(candidate.eligibility) && candidate.eligibility.length
        ? candidate.eligibility
        : ["Open to public"],
    duration: candidate.duration?.trim() || FALLBACKS.duration,
    funding: candidate.funding?.trim() || FALLBACKS.funding,
    selectivity: candidate.selectivity?.trim() || FALLBACKS.selectivity,
    cohortSize: candidate.cohortSize ?? null,
    deadline: candidate.deadline?.trim() || FALLBACKS.deadline,
    deadlines: candidate.deadlines,
    website: candidate.website,
    applicationLink: candidate.applicationLink,
    associatedCenter: candidate.associatedCenter,
    tags: candidate.tags,
    lastUpdated: candidate.lastUpdated,
    sourceUrl: candidate.sourceUrl,
  };
}

async function loadAll() {
  if (!existsSync(CRAWLED_DIR)) return [];
  const files = (await readdir(CRAWLED_DIR)).filter((f) => f.endsWith(".json"));
  const all = [];
  for (const file of files) {
    const raw = JSON.parse(await readFile(join(CRAWLED_DIR, file), "utf-8"));
    for (const c of raw.candidates ?? []) all.push(c);
  }
  return all;
}

const candidates = await loadAll();

// Dedupe by id (campus-prefixed, globally unique). Slug alone collides
// cross-campus when two hubs publish a "Venture Lab" page; id is what
// the routes use, so it's the right uniqueness key. Input order is
// stable (alphabetical by campus filename), so earlier wins.
const seen = new Map();
for (const c of candidates) {
  const program = coerce(c);
  if (!seen.has(program.id)) seen.set(program.id, program);
}

const programs = [...seen.values()].toSorted((a, b) =>
  (a.campus + a.name).localeCompare(b.campus + b.name),
);

const generatedAt = new Date().toISOString();

const banner = `// AUTO-GENERATED by \`vp run build-data\`. Do not edit by hand.
// Source: data/crawled/*.json — last refresh: ${generatedAt}
// Run \`vp run crawl\` followed by \`vp run build-data\` to refresh.`;

const body = `import type { Program } from "./types";

export const CRAWLED_PROGRAMS: Program[] = ${JSON.stringify(programs, null, 2)};

export const CRAWLED_AT: string | null = ${JSON.stringify(generatedAt)};
`;

await writeFile(OUT, `${banner}\n${body}`);

console.log(`Wrote ${programs.length} program(s) → ${OUT}`);
