#!/usr/bin/env node
//
// Read every data/crawled/<campus>.json file produced by run.ts, normalize
// the candidates, dedupe by id across campuses, and emit a single typed
// TypeScript module the React app imports at build time:
//
//   src/data/programs.generated.ts
//
// The UI's `mergePrograms` helper (src/data/normalize.ts) reconciles the
// generated list with the curated PROGRAMS array — curated wins on conflict.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import {
  coerceToProgram,
  isRejectedProgramName,
  type ProgramCandidate,
} from "../../src/data/normalize.ts";
import type { Program } from "../../src/data/types.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");
const CRAWLED_DIR = join(ROOT, "data", "crawled");
const OUT = join(ROOT, "src", "data", "programs.generated.ts");

interface CrawledFile {
  campus: string;
  candidates?: ProgramCandidate[];
}

async function loadAll(): Promise<ProgramCandidate[]> {
  if (!existsSync(CRAWLED_DIR)) return [];
  const files = (await readdir(CRAWLED_DIR)).filter((f) => f.endsWith(".json"));
  const all: ProgramCandidate[] = [];
  for (const file of files) {
    const raw = JSON.parse(await readFile(join(CRAWLED_DIR, file), "utf-8")) as CrawledFile;
    for (const c of raw.candidates ?? []) all.push(c);
  }
  return all;
}

const candidates = await loadAll();

// Dedupe by id (campus-prefixed, globally unique). Slug alone collides
// cross-campus when two hubs publish a "Venture Lab" page; id is what
// the routes use, so it's the right uniqueness key. Input order is
// stable (alphabetical by campus filename), so earlier wins.
const seen = new Map<string, Program>();
for (const c of candidates) {
  // Drop section/navigation pages (e.g. "News and Events") that slipped past
  // the crawler's keyword gate before they reach the shipped catalog.
  if (isRejectedProgramName(c.name)) continue;
  const program = coerceToProgram(c);
  if (!seen.has(program.id)) seen.set(program.id, program);
}

const programs = [...seen.values()].toSorted((a, b) =>
  (a.campus + a.name).localeCompare(b.campus + b.name),
);

const generatedAt = new Date().toISOString();

const banner = `// AUTO-GENERATED by \`vp run build-data\`. Do not edit by hand.
// Source: data/crawled/*.json — last refresh: ${generatedAt}
// Run \`vp run crawl\` followed by \`vp run build-data\` to refresh.`;

const body = `import type { Program } from "./types.ts";

export const CRAWLED_PROGRAMS: Program[] = ${JSON.stringify(programs, null, 2)};

export const CRAWLED_AT: string | null = ${JSON.stringify(generatedAt)};
`;

await writeFile(OUT, `${banner}\n${body}`);

console.log(`Wrote ${programs.length} program(s) → ${OUT}`);
