// AUTO-GENERATED by `vp run build-news-data`. Do not edit by hand.
// Source: data/news/*.json — last refresh: 2026-06-14T13:41:23.202Z
// Run `vp run crawl:news` followed by `vp run build-news-data` to refresh.
import type { NewsItem } from "./news.ts";

export const NEWS: NewsItem[] = [
  {
    "id": "berkeley-13-5-million-commitment-expands-support-for-citris-cdss-innovation-fellowships",
    "campus": "berkeley",
    "title": "$13.5 million commitment expands support for CITRIS-CDSS Innovation Fellowships",
    "summary": "$13.5 million commitment expands support for CITRIS-CDSS Innovation Fellowships",
    "publishedAt": "2026-06-11T21:54:00.000Z",
    "sourceUrl": "https://citris-uc.org/13-5-million-commitment-expands-support-for-citris-cdss-innovation-fellowships/?utm_source=rss&utm_medium=rss&utm_campaign=13-5-million-commitment-expands-support-for-citris-cdss-innovation-fellowships",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2025/09/2025aic-banner-1540x368px-768x184.jpg",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "berkeley-making-the-invisible-visible",
    "campus": "berkeley",
    "title": "Making the invisible visible",
    "summary": "A landmark achievement in microscopy is poised to reveal the molecular machinery of life inside cells, at near-atomic detail. Inside every living cell, tens of thousands of different types of…",
    "publishedAt": "2026-06-11T19:27:00.000Z",
    "sourceUrl": "https://qb3.berkeley.edu/news/making-the-invisible-visible/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/apoferritin-cryo-em-xlpp-lasers-off-on-contrast-comparison-biohub-768x960.png",
    "sourceHost": "qb3.berkeley.edu"
  },
  {
    "id": "berkeley-uc-berkeley-haas-celebrates-emba-class-of-2026-at-commencement",
    "campus": "berkeley",
    "title": "UC Berkeley Haas celebrates EMBA Class of 2026 at commencement",
    "summary": "The 2026 EMBA cohort breaks for a photo with EMBA staff. Photo: Noah Berger Berkeley Haas Executive MBA students in the tight-knit class of 2026 graduated last Saturday, celebrating months…",
    "publishedAt": "2026-06-11T00:13:00.000Z",
    "sourceUrl": "https://newsroom.haas.berkeley.edu/uc-berkeley-haas-celebrates-emba-class-of-2026-at-commencement/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/bkw_0282b-scaled-768x347.jpg",
    "sourceHost": "newsroom.haas.berkeley.edu"
  },
  {
    "id": "berkeley-citris-to-co-host-whats-next-longevity-venture-summit",
    "campus": "berkeley",
    "title": "CITRIS to co-host What’s Next Longevity Venture Summit",
    "summary": "CITRIS to co-host What’s Next Longevity Venture Summit",
    "publishedAt": "2026-06-10T16:04:00.000Z",
    "sourceUrl": "https://citris-uc.org/citris-to-co-host-whats-next-longevity-venture-summit/?utm_source=rss&utm_medium=rss&utm_campaign=citris-to-co-host-whats-next-longevity-venture-summit",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/Longevity-Summit-June-2026-768x183.png",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "berkeley-colton-hess-mba-26",
    "campus": "berkeley",
    "title": "Colton Hess, MBA 26",
    "summary": "In recent months, Colton Hess, MBA/MPH 26, has taught more than 50 students across Haas to use Claude Code through AI “activation sessions.” Their enthusiasm inspired led Hess to launch…",
    "publishedAt": "2026-06-09T20:54:00.000Z",
    "sourceUrl": "https://newsroom.haas.berkeley.edu/colton-hess-mba-26/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/colton-4-scaled-768x512.jpg",
    "sourceHost": "newsroom.haas.berkeley.edu"
  },
  {
    "id": "berkeley-earthquakes-hurricanes-and-floods-meet-the-newest-mdeveng-professor-whos-no-stranger-to-disasters",
    "campus": "berkeley",
    "title": "Earthquakes, Hurricanes, and Floods: Meet the newest MDevEng professor who’s no stranger to disasters",
    "summary": "A new member of the Graduate Group in Development Engineering, Ceferino and his team move in after disasters, working on the ground to understand how and why infrastructure fails —…",
    "publishedAt": "2026-06-08T21:18:00.000Z",
    "sourceUrl": "https://blumcenter.berkeley.edu/earthquakes-hurricanes-and-floods-meet-the-newest-mdeveng-professor-whos-no-stranger-to-disasters/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/Turkey.png",
    "sourceHost": "blumcenter.berkeley.edu"
  },
  {
    "id": "berkeley-how-gpp-graduate-yesenia-casillas-rios-molds-the-public-spaces-she-grew-up-with",
    "campus": "berkeley",
    "title": "How GPP Graduate Yesenia Casillas Rios Molds the Public Spaces She Grew Up With",
    "summary": "Casillas Rios, a three-year student fellow at the Blum Center, graduated this May from the Global Poverty & Practice minor. Since high school, she’s been committed to enhancing the quality…",
    "publishedAt": "2026-06-08T20:40:00.000Z",
    "sourceUrl": "https://blumcenter.berkeley.edu/how-gpp-graduate-yesenia-casillas-rios-molds-the-public-spaces-she-grew-up-with/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/Yesenia.png",
    "sourceHost": "blumcenter.berkeley.edu"
  },
  {
    "id": "berkeley-decarbonization-down-under",
    "campus": "berkeley",
    "title": "Decarbonization Down Under",
    "summary": "The post Decarbonization Down Under appeared first on Haas News | UC Berkeley Haas. Source link",
    "publishedAt": "2026-06-08T19:33:00.000Z",
    "sourceUrl": "https://energyathaas.wordpress.com/2026/06/08/decarbonization-down-under/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/rooftop-solar-1-768x429.jpg",
    "sourceHost": "energyathaas.wordpress.com"
  },
  {
    "id": "berkeley-uc-santa-cruz-slugiculture-named-a-finalist-in-farm-robotics-challenge",
    "campus": "berkeley",
    "title": "UC Santa Cruz ‘Slugiculture’ named a finalist in Farm Robotics Challenge",
    "summary": "UC Santa Cruz ‘Slugiculture’ named a finalist in Farm Robotics Challenge",
    "publishedAt": "2026-06-08T16:02:00.000Z",
    "sourceUrl": "https://citris-uc.org/uc-santa-cruz-slugiculture-named-a-finalist-in-farm-robotics-challenge/?utm_source=rss&utm_medium=rss&utm_campaign=uc-santa-cruz-slugiculture-named-a-finalist-in-farm-robotics-challenge",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/UC-Santa-Cruz-Farm-Robotics-Challenge-June-2026-768x184.png",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "berkeley-lucas-chagas-vital-mba-18-finding-inclusion-and-community",
    "campus": "berkeley",
    "title": "Lucas Chagas Vital, MBA 18 – Finding Inclusion and Community",
    "summary": "The post Lucas Chagas Vital, MBA 18 – Finding Inclusion and Community appeared first on Haas News | UC Berkeley Haas. Source link",
    "publishedAt": "2026-06-04T19:34:00.000Z",
    "sourceUrl": "https://haaspodcasts.org/podcast/lucas-chagas-vital-mba-18-finding-inclusion-and-community/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/06/Lucas-Chagas-Vital-Episode-Artwork-768x768.png",
    "sourceHost": "haaspodcasts.org"
  },
  {
    "id": "sd-what-desert-locusts-reveal-about-disaster-monitoring",
    "campus": "sd",
    "title": "What Desert Locusts Reveal About Disaster Monitoring",
    "summary": "A new working paper co-authored by Gordon McCord of the UC San Diego School of Global Policy and Strategy suggests that the greatest benefits of disaster monitoring may come from catastrophes the world never sees.",
    "publishedAt": "2026-06-02T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/what-desert-locusts-reveal-about-disaster-monitoring",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Desert-Locust-Swarm-photo-by-Magnus_Ullman_CC_BY-SA_3.0_via_Wikimedia_Commons_.png",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "santabarbara-aelumas-ceo-jonathan-klamkin-receive-iprm-award",
    "campus": "santabarbara",
    "title": "Aeluma’s CEO Jonathan Klamkin to Receive IPRM Award",
    "summary": "Aeluma’s CEO Jonathan Klamkin to Receive IPRM Award gmundaden Mon, 06/01/2026 - 10:15 Aeluma, Inc. (NASDAQ: ALMU), a semiconductor company specializing in high-performance, scalable technologies for mobile, AI, defense and aerospace, robotics, automotive, AR/VR, and quantum, announced today that President and CEO Jonathan Klamkin, Ph.D. will receive the prestigious Indium Phosphide and Related Mat",
    "publishedAt": "2026-06-01T17:15:10.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/aelumas-ceo-jonathan-klamkin-receive-iprm-award",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-06/images.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "sd-in-the-worlds-economic-black-holes-data-still-leaks-out",
    "campus": "sd",
    "title": "In the World’s Economic “Black Holes,” Data Still Leaks Out",
    "summary": "From satellite imagery to clandestine price reports, a new study from the School of Global Policy and Strategy at UC San Diego draws on North Korea to explore economic activity in opaque regimes and information-scarce regions.",
    "publishedAt": "2026-05-28T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/in-the-worlds-economic-black-holes-data-still-leaks-out",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/North-Korea-Flag-Barbed-Wire-photo-by-iStock_Diy13-1200-CROP-2187644088.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "sd-10-speakers-10-weeks-countless-career-lessons-from-fellow-tritons",
    "campus": "sd",
    "title": "10 Speakers, 10 Weeks, Countless Career Lessons from Fellow Tritons",
    "summary": "Students often hear about the importance of networking for career success — but what does that actually look like? A new course launched by the Department of Economics in the School of Social Sciences gives students the chance to connect with accomplished professionals directly in the classroom.",
    "publishedAt": "2026-05-28T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/10-speakers-10-weeks-countless-career-lessons-from-fellow-tritons",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/230607GPS-DSC_9581ErikJepsenUCSanDiego191%281%29%281%29.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "merced-projects-make-world-better-promoted-merced-2-market",
    "campus": "merced",
    "title": "Projects to Make the World Better Promoted at Merced 2 Market",
    "summary": "By Patty Guerra, UC Merced May 27, 2026 The event highlighted projects aimed at helping people and communities solve problems. An artificial intelligence-powered system to ensure the safety of the elderly while still providing privacy. Wearable muscle monitoring to speed recovery from injury. A chemical-free method of putting out fires. A more effective way to detect methane leaks. These were just",
    "publishedAt": "2026-05-27T18:05:03.000Z",
    "sourceUrl": "https://news.ucmerced.edu/news/2026/projects-make-world-better-promoted-merced-2-market",
    "imageUrl": "https://news.ucmerced.edu/sites/g/files/ufvvjh1306/f/news/image/ucm_merced_2_market_hero.jpeg",
    "sourceHost": "news.ucmerced.edu"
  },
  {
    "id": "sd-risk-or-reward-first-thing-people-want-to-know-when-decision-is-uncertain",
    "campus": "sd",
    "title": "Risk or Reward: What’s the First Thing People Want to Know When a Decision Is Uncertain?",
    "summary": "In a new paper, Uma Karmarkar and colleagues ask a deceptively simple question: When people face an uncertain opportunity, what information do they want to see first – the potential reward, or the odds of getting it?",
    "publishedAt": "2026-05-26T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/risk-or-reward-first-thing-people-want-to-know-when-decision-is-uncertain",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Hand-Throwing-Dice-photo-by-iStock_Tero-Vesalainen-1174418152.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "davis-uc-davis-stair-health-program-invests-faculty-led-health-innovations",
    "campus": "davis",
    "title": "UC Davis STAIR HEALTH Program Invests in Faculty-led Health Innovations",
    "summary": "UC Davis Health awarded more than $390,000 through its STAIR HEALTH proof-of-concept program to support three interdisciplinary research teams advancing promising innovations in cancer imaging, spinal cord injury treatment and breast cancer therapeutics toward commercial and clinical impact.",
    "publishedAt": "2026-05-21T15:35:24.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-stair-health-program-invests-faculty-led-health-innovations",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/2025-07-01_48X29.jpg?h=36f8b718&itok=NM0BJTFI",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "sd-mba-students-take-on-real-consulting-work-at-the-rady-school",
    "campus": "sd",
    "title": "MBA Students Take On Real Consulting Work at the Rady School",
    "summary": "At UC San Diego’s Rady School of Management, students in a required program work directly with companies across San Diego, delivering recommendations that shape business decisions.",
    "publishedAt": "2026-05-14T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/mba-students-take-on-real-consulting-work-at-the-rady-school",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Rady-Action-Project-Sp2026-DSC09247-1200crop.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "sf-how-impossible-idea-led-pancreatic-cancer-breakthrough",
    "campus": "sf",
    "title": "How an ‘Impossible’ Idea Led to a Pancreatic Cancer Breakthrough",
    "summary": "How an ‘Impossible’ Idea Led to a Pancreatic Cancer Breakthrough",
    "publishedAt": "2026-05-12T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/how-impossible-idea-led-pancreatic-cancer-breakthrough",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "davis-uc-davis-born-amplifye-targets-new-frontier-protein-efficiency-amid-glp-1-era",
    "campus": "davis",
    "title": "UC Davis–born amplifye Targets a New Frontier in Protein Efficiency Amid GLP-1 Era",
    "summary": "Born out of cross-disciplinary research at University of California, Davis, startup amplifye is developing enzyme-based technology designed to improve protein absorption and muscle health as growing use of GLP-1 therapies reshapes nutrition and metabolic health needs.",
    "publishedAt": "2026-05-11T15:30:03.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-born-amplifye-targets-new-frontier-protein-efficiency-amid-glp-1-era",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/amplifye%20article%20image_1280x720.jpg?h=3e07f1d9&itok=rPIUdxsO",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "irvine-cytoseen",
    "campus": "irvine",
    "title": "Seeing the Unseen in Disease",
    "summary": "UC Irvine startup Cytoseen detects new drug targets for cancer and neurodegeneration.",
    "publishedAt": "2026-05-08T22:46:18.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/cytoseen/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/05/Cytoseen-scaled.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "sd-missing-information-can-misinform",
    "campus": "sd",
    "title": "Missing Information Can Misinform",
    "summary": "In the online attention economy, new research from the UC San Diego Rady School finds that making science more clickable or shareable can help some readers learn more – but leaves many others with an incomplete understanding.",
    "publishedAt": "2026-05-07T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/missing-information-can-misinform",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Missing-Puzzle-Piece-photo-by-iStock_Seng_kui_Lim-1658897093.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "santabarbara-beacon-photonics-first-industry-member-ucsb-oasis",
    "campus": "santabarbara",
    "title": "Beacon Photonics First Industry Member at UCSB OASIS",
    "summary": "Beacon Photonics First Industry Member at UCSB OASIS gmundaden Mon, 05/04/2026 - 10:15 Beacon Photonics has become the first industry member of OASIS, UC Santa Barbara’s new innovation and translational research hub, marking an early milestone for the 105,000-square-foot facility designed to bring together established companies, startups, and academic researchers. Managed by The Robert Mehrabian C",
    "publishedAt": "2026-05-04T17:15:57.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/beacon-photonics-first-industry-member-ucsb-oasis",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-05/BEACON_OASIS.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-new-venture-competition-finalists-2026",
    "campus": "santabarbara",
    "title": "New Venture Competition Finalists 2026",
    "summary": "New Venture Competition Finalists 2026 gmundaden Wed, 04/29/2026 - 11:41 Congrats to the New Venture Competition Finalists of 2026! Register for the New Venture Finals, Wednesday, May 20, 2026 at 3:30 PM PST in Corwin Pavilion. MediMRF is a modular, AI-enabled waste-sorting system for hospitals, automating the identification and removal of hazardous materials from waste streams. mimic is building",
    "publishedAt": "2026-04-29T18:41:35.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/new-venture-competition-finalists-2026",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-04/Untitled%20design_0.png",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "irvine-born-in-california-2026",
    "campus": "irvine",
    "title": "The Pipeline",
    "summary": "What does it take to make a UC idea matter in the real world?",
    "publishedAt": "2026-04-29T16:30:40.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/born-in-california-2026/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2023/01/Neried-biomaterials1.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "sf-qa-nicholas-hertz-president-ceo-montara-therapeutics",
    "campus": "sf",
    "title": "Q&A with Nicholas Hertz, President & CEO of Montara Therapeutics",
    "summary": "Q&A with Nicholas Hertz, President & CEO of Montara Therapeutics",
    "publishedAt": "2026-04-29T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/qa-nicholas-hertz-president-ceo-montara-therapeutics",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-breakthrough-device-designation-aidabreastr-early-stage-invasive-breast-cancer-assay",
    "campus": "sf",
    "title": "Breakthrough Device Designation for AidaBREAST® - Early-Stage Invasive Breast Cancer Assay",
    "summary": "Breakthrough Device Designation for AidaBREAST® - Early-Stage Invasive Breast Cancer Assay",
    "publishedAt": "2026-04-29T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/breakthrough-device-designation-aidabreastr-early-stage-invasive-breast-cancer-assay",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "irvine-ecotune",
    "campus": "irvine",
    "title": "The Material Question",
    "summary": "What if materials weren’t just made, but designed in tune with nature?",
    "publishedAt": "2026-04-24T22:38:57.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/ecotune/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/04/Ecotune-scaled.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "santabarbara-techtopia-2026-showcases-ucsbs-expanding-innovation-ecosystem",
    "campus": "santabarbara",
    "title": "TechTopia 2026 Showcases UCSB’s Expanding Innovation Ecosystem",
    "summary": "TechTopia 2026 Showcases UCSB’s Expanding Innovation Ecosystem gmundaden Wed, 04/22/2026 - 11:09 That desire for collaboration was the through-line of TechTopia 2026, a half-day summit featuring tours, demonstrations, and talks from leaders tied to UC Santa Barbara, Google Quantum AI, Agilent Technologies, AppFolio, and other firms with roots on the South Coast. It also doubled as something of a p",
    "publishedAt": "2026-04-22T18:09:38.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/techtopia-2026-showcases-ucsbs-expanding-innovation-ecosystem",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-04/download.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "sf-ucb-acquire-neurona-therapeutics-advancing-its-innovative-leadership-epilepsy-through",
    "campus": "sf",
    "title": "UCB to acquire Neurona Therapeutics, advancing its innovative leadership in epilepsy through regenerative science",
    "summary": "UCB to acquire Neurona Therapeutics, advancing its innovative leadership in epilepsy through regenerative science",
    "publishedAt": "2026-04-17T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ucb-acquire-neurona-therapeutics-advancing-its-innovative-leadership-epilepsy-through",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "irvine-sounddose",
    "campus": "irvine",
    "title": "The Blind Spot in Modern Radiation Therapy",
    "summary": "How UC Irvine startup SoundDose is tackling one of cancer care’s biggest unknowns",
    "publishedAt": "2026-04-15T19:13:47.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/sounddose/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/04/Sound-Dose.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "la-ucla-anderson-school-management-launches-minors-real-estate-and-sports-leadership-and-management",
    "campus": "la",
    "title": "UCLA Anderson School of Management Launches Minors in Real Estate and Sports Leadership and Management",
    "summary": "The two new minors expand the school’s undergraduate offerings, which include minors in Accounting and Entrepreneurship",
    "publishedAt": "2026-04-15T19:00:00.000Z",
    "sourceUrl": "https://www.anderson.ucla.edu/news-and-events/ucla-anderson-school-management-launches-minors-real-estate-and-sports-leadership-and-management",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/social_og/public/image/2026-04/20260415-campus-drone-card.jpg.jpeg?itok=QzAacVws",
    "sourceHost": "www.anderson.ucla.edu"
  },
  {
    "id": "davis-uc-davis-launches-aggie-venture-accelerator-advance-early-stage-life-science-innovation",
    "campus": "davis",
    "title": "UC Davis Launches Aggie Venture Accelerator to Advance Early Stage Life Science Innovation",
    "summary": "The UC Davis Innovation and Economic Development Office has launched the Aggie Venture Accelerator, an initiative designed to support early stage startups developing solutions at the intersection of life science, food and health.",
    "publishedAt": "2026-04-13T16:15:36.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-launches-aggie-venture-accelerator-advance-early-stage-life-science-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_1788_reduced.jpg?h=37bd9af6&itok=3XXTuw-j",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-aggie-square-partners-release-first-community-benefits-progress-report-highlighting-early",
    "campus": "davis",
    "title": "Aggie Square Partners Release First Community Benefits Progress Report Highlighting Early Impact",
    "summary": "The first Aggie Square Community Benefits Partnership Agreement (CBPA) Annual Progress Report has been released by UC Davis, the City of Sacramento and Wexford Science & Technology, documenting significant progress towards meeting many of the goals outlined in the CBPA.",
    "publishedAt": "2026-04-02T22:40:20.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/aggie-square-partners-release-first-community-benefits-progress-report-highlighting-early",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_6025.jpg?h=4997dc06&itok=8Y1gDdgI",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "irvine-mifti",
    "campus": "irvine",
    "title": "The $40 Trillion Question",
    "summary": "Can MIFTI, a scrappy UC Irvine-based startup, outpace billion-dollar fusion giants?",
    "publishedAt": "2026-03-30T22:53:07.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/mifti/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/03/MIFTI-1.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "davis-uc-davis-health-ventures-appoints-troels-adrian-strengthen-industry-partnerships-and-advance",
    "campus": "davis",
    "title": "UC Davis Health Ventures Appoints Troels Adrian to Strengthen Industry Partnerships and Advance the UC Davis Health Clinical Test Bed",
    "summary": "UC Davis Health Ventures, part of the Innovation and Economic Development Office at UC Davis, today announced the appointment of Troels Adrian as Director of Industry Engagement.",
    "publishedAt": "2026-03-23T15:18:26.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-health-ventures-appoints-troels-adrian-strengthen-industry-partnerships-and-advance",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Troels%20Adrian%20COLOR.jpg?h=d73b4fec&itok=cVMoxhzz",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-food-health-angels-network-launches-accelerate-science-driven-food-and-health-innovation",
    "campus": "davis",
    "title": "Food & Health Angels Network Launches to Accelerate Science-Driven Food and Health Innovation",
    "summary": "Introducing the Food & Health Angels Network, a groundbreaking initiative launched to accelerate science-driven innovations in food and health, addressing the pressing issue of metabolic disease.",
    "publishedAt": "2026-03-19T16:15:08.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/food-health-angels-network-launches-accelerate-science-driven-food-and-health-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/real-food-pyramid-arrangement.jpg?h=5313cdcb&itok=vL82Pgy9",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "sf-ucsf-receives-824m-nih-funding-driving-medical-breakthroughs",
    "campus": "sf",
    "title": "UCSF Receives $824M in NIH Funding, Driving Medical Breakthroughs",
    "summary": "UCSF Receives $824M in NIH Funding, Driving Medical Breakthroughs -",
    "publishedAt": "2026-03-13T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ucsf-receives-824m-nih-funding-driving-medical-breakthroughs",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-vs3-medical-announces-first-patients-enrolled-first-human-study-novel-neurovascular",
    "campus": "sf",
    "title": "VS3 Medical Announces First Patients Enrolled in First-in-Human Study of Novel Neurovascular Implant to Address Symptomatic Venous Sinus Stenosis",
    "summary": "VS3 Medical Announces First Patients Enrolled in First-in-Human Study of Novel Neurovascular Implant to Address Symptomatic Venous Sinus Stenosis",
    "publishedAt": "2026-03-10T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/vs3-medical-announces-first-patients-enrolled-first-human-study-novel-neurovascular",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "irvine-neuroqure",
    "campus": "irvine",
    "title": "A New Signal for Autism",
    "summary": "How UC Irvine research and a father’s story are changing the timeline of care",
    "publishedAt": "2026-02-27T20:40:15.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/neuroqure/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/02/NeuroQure-2.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "irvine-eira-bio",
    "campus": "irvine",
    "title": "Is This the Breakthrough Drug Development We’ve Been Waiting For?",
    "summary": "Eira Bio is targeting membrane proteins long considered unreachable by antibody drugs.",
    "publishedAt": "2026-02-17T18:32:41.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/eira-bio/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/02/Eira-Bio-1.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "irvine-vena-vitals",
    "campus": "irvine",
    "title": "Can Wearable Tech Finally Get Blood Pressure Right?",
    "summary": "Forget the cuff. Vena Vitals’ sticker-like sensor aims to deliver ICU-level data without ever breaking the skin.",
    "publishedAt": "2026-02-17T17:42:05.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/vena-vitals/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/02/Vena-Vitals-1.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "davis-uc-davis-highlights-translational-breakthroughs-and-startups-8th-annual-biotech-innovation",
    "campus": "davis",
    "title": "UC Davis Highlights Translational Breakthroughs and Startups at the 8th Annual Biotech Innovation Gallery",
    "summary": "UC Davis showcased groundbreaking translational research and innovative biotech startups at the 8th Annual Biotech Innovation Gallery in San Francisco. Hosted by the UC Davis Innovation and Economic Development Office, the event brought in over 330 attendees to connect with and explore potential partnerships with researchers and startup founders, aligning with the J.P. Morgan Healthcare Conference",
    "publishedAt": "2026-02-10T16:51:50.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-highlights-translational-breakthroughs-and-startups-8th-annual-biotech-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/David%20Segal_BIG.jpg?h=9c4c0580&itok=cZtQYKZp",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "irvine-summit-tech",
    "campus": "irvine",
    "title": "When Reality is the Canvas",
    "summary": "How Aditi Majumder is Building the Ultimate 3D Experience",
    "publishedAt": "2026-01-22T16:00:01.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/summit-tech/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2025/12/STL-image-1.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "sf-tahoe-therapeutics-and-alloy-therapeutics-form-joint-venture-and-develop-first-class",
    "campus": "sf",
    "title": "Tahoe Therapeutics and Alloy Therapeutics to Form Joint Venture and Develop First-in-Class Antibody-Drug Conjugates for Hard-to-Treat Cancers",
    "summary": "Tahoe Therapeutics and Alloy Therapeutics to Form Joint Venture and Develop First-in-Class Antibody-Drug Conjugates for Hard-to-Treat Cancers",
    "publishedAt": "2026-01-14T08:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/tahoe-therapeutics-and-alloy-therapeutics-form-joint-venture-and-develop-first-class",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "santabarbara-professor-phillip-christopher-and-stephen-wilson-named-among-worlds-most-influential",
    "campus": "santabarbara",
    "title": "Professor Phillip Christopher and Stephen Wilson Named Among the World’s Most Influential Researchers",
    "summary": "Professor Phillip Christopher and Stephen Wilson Named Among the World’s Most Influential Researchers gmundaden Tue, 01/13/2026 - 11:24 Both Christopher and Wilson, who appear on the list for the first time, were recognized in the cross-field category, which honors researchers whose publications span multiple disciplines, reflecting the importance of interdisciplinary research. The annual list com",
    "publishedAt": "2026-01-13T19:24:05.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/professor-phillip-christopher-and-stephen-wilson-named-among-worlds-most-influential",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/2025_highly_cited.png",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-ucsb-associate-professor-chemistry-and-biochemistry-grace-han-named-moore-inventor-fellow",
    "campus": "santabarbara",
    "title": "UCSB Associate Professor of Chemistry and Biochemistry Grace Han named Moore Inventor Fellow",
    "summary": "UCSB Associate Professor of Chemistry and Biochemistry Grace Han named Moore Inventor Fellow gmundaden Tue, 01/13/2026 - 11:05 Han’s research centers on molecular solar thermal energy storage, developing fuels that can capture sunlight, store it in chemical bonds, and later release it as heat on demand. The approach offers a clean, emission-free alternative to fossil fuels for residential and indu",
    "publishedAt": "2026-01-13T19:05:16.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/ucsb-associate-professor-chemistry-and-biochemistry-grace-han-named-moore-inventor-fellow",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/Grace-Han_opt.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-ucsb-professor-blumenthals-lab-selected-nsfs-national-quantum-virtual-laboratory",
    "campus": "santabarbara",
    "title": "UCSB Professor Blumenthal’s Lab Selected for NSF's National Quantum Virtual Laboratory",
    "summary": "UCSB Professor Blumenthal’s Lab Selected for NSF's National Quantum Virtual Laboratory gmundaden Tue, 01/13/2026 - 10:58 Aligning with colleagues at MIT, UCLA, Harvard and University of Maryland, Blumenthal’s lab joins federal agencies and partners from the private sector to design high-tech infrastructure across the country in an effort to accelerate the development of useful quantum technologies",
    "publishedAt": "2026-01-13T18:58:18.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/ucsb-professor-blumenthals-lab-selected-nsfs-national-quantum-virtual-laboratory",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/blumenthal.png",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-fda-clears-osteoprober-first-ever-device-indication-measuring-bone-material-strength",
    "campus": "santabarbara",
    "title": "FDA Clears OsteoProbe®: First-Ever Device Indication for Measuring Bone Material Strength",
    "summary": "FDA Clears OsteoProbe®: First-Ever Device Indication for Measuring Bone Material Strength gmundaden Tue, 01/13/2026 - 10:46 Active Life Scientific, Inc. (ALSI), a leader in innovative medical devices for bone quality, today announced that the U.S. Food and Drug Administration (FDA) has granted a new 510(k) clearance (K250216) for OsteoProbe®, marking a historic milestone as the first device with a",
    "publishedAt": "2026-01-13T18:46:05.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/fda-clears-osteoprober-first-ever-device-indication-measuring-bone-material-strength",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/Group-416.png",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-ucsb-professor-kevin-plaxco-elected-fellow-national-academy-inventors",
    "campus": "santabarbara",
    "title": "UCSB Professor Kevin Plaxco Elected Fellow of National Academy of Inventors",
    "summary": "UCSB Professor Kevin Plaxco Elected Fellow of National Academy of Inventors gmundaden Tue, 01/13/2026 - 10:22 The Plaxco Lab developed a patch-like sensing technology, similar to a glucose monitor worn by many diabetics. It's designed to help prevent underdosing or overdosing through the use of electrochemical biosensors. The device is now in clinical trials being conducted by a company in Melbour",
    "publishedAt": "2026-01-13T18:22:06.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/ucsb-professor-kevin-plaxco-elected-fellow-national-academy-inventors",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/KevinPlaxco.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "sf-montara-therapeutics-announces-development-candidate-first-brainonlytm-enabled-program",
    "campus": "sf",
    "title": "Montara Therapeutics Announces Development Candidate for First BrainOnly™-Enabled Program in TSC-Related Epilepsy and Appoints Chief Business Officer",
    "summary": "Montara Therapeutics Announces Development Candidate for First BrainOnly™-Enabled Program in TSC-Related Epilepsy and Appoints Chief Business Officer",
    "publishedAt": "2025-12-10T08:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/montara-therapeutics-announces-development-candidate-first-brainonlytm-enabled-program",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-alice-tang-made-forbes-30-under-30-list-science",
    "campus": "sf",
    "title": "Alice Tang Made the Forbes 30 Under 30 List in Science",
    "summary": "Alace Tang achieved the Forbes 30 Under 30 in Science",
    "publishedAt": "2025-12-09T08:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/alice-tang-made-forbes-30-under-30-list-science",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "davis-uc-davis-announces-winners-autumn-2025-science-translation-and-innovative-research-grant",
    "campus": "davis",
    "title": "UC Davis Announces Winners of Autumn 2025 Science Translation and Innovative Research Grant Program",
    "summary": "The University of California, Davis, has awarded $100,000 through the autumn 2025 cohort of the Science Translation and Innovative Research (STAIR) Grant Program to help scientists advance innovative research with strong commercial potential.",
    "publishedAt": "2025-12-08T20:48:03.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-announces-winners-autumn-2025-science-translation-and-innovative-research-grant",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Baar_Abhaya.jpg?h=52d3fcb6&itok=7en2k7q-",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "santabarbara-aeluma-joins-midwest-microelectronics-consortium",
    "campus": "santabarbara",
    "title": "Aeluma Joins the Midwest Microelectronics Consortium",
    "summary": "Aeluma Joins the Midwest Microelectronics Consortium gmundaden Tue, 12/02/2025 - 10:38 Aeluma, Inc. (NASDAQ: ALMU), a semiconductor company specializing in high-performance, scalable technologies for mobile, AI, defense and aerospace, robotics, automotive, AR/VR, and quantum computing, today announced that it has joined the Midwest Microelectronics Consortium (MMEC), a leading hub of microelectron",
    "publishedAt": "2025-12-02T18:38:37.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/aeluma-joins-midwest-microelectronics-consortium",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-12/image%282%29.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "irvine-zeppelin-floods",
    "campus": "irvine",
    "title": "When the Levee Breaks",
    "summary": "What if everyone could plan infrastructure?",
    "publishedAt": "2025-12-02T16:00:20.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/zeppelin-floods/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2025/11/Zeppelin-Floods.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "davis-venture-catalyst-fuels-record-year-uc-davis-innovation-startups",
    "campus": "davis",
    "title": "Venture Catalyst Fuels Record Year for UC Davis Innovation Startups",
    "summary": "At Venture Catalyst, part of the UC Davis Innovation and Economic Development Office, we're proud to support the translation of UC Davis research and technology into real-world applications by fostering the development of new ventures. Through strategic collaborations, training and mentorship programs, funding translational research, and proactive outreach, we foster the university’s entrepreneuri",
    "publishedAt": "2025-10-30T15:49:44.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/venture-catalyst-fuels-record-year-uc-davis-innovation-startups",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/VC%20Stats.png?h=c673cd1c&itok=x8MxJRRm",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-discovery-forum-highlights-how-uc-davis-center-glp-1-and-metabolic-health-innovation",
    "campus": "davis",
    "title": "Discovery Forum Highlights How UC Davis Is at the Center of GLP-1 and Metabolic Health Innovation",
    "summary": "The Discovery Forum showcased UC Davis as a leader in GLP-1 and metabolic health innovation, bringing together researchers, industry experts, and investors to explore how metabolic hormones are reshaping health and nutrition. With cutting-edge research, world-class facilities, and a strong innovation ecosystem, the event was a reminder of UC Davis’ unique ability to translate metabolic science int",
    "publishedAt": "2025-10-15T20:10:27.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/discovery-forum-highlights-how-uc-davis-center-glp-1-and-metabolic-health-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/IMG_5290.jpg?h=5dc9785f&itok=LuFfzZNo",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-uc-davis-healths-ifm-fund-backs-delix-therapeutics-first-investment",
    "campus": "davis",
    "title": "UC Davis Health’s IFM Fund Backs Delix Therapeutics in First Investment",
    "summary": "UC Davis Health Ventures, part of the Innovation and Economic Development Office (IEDO) at the University of California, Davis, today announced the first investment from its Investing in the Future of Medicine (IFM) Fund, backing Delix Therapeutics.",
    "publishedAt": "2025-10-02T16:10:43.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-healths-ifm-fund-backs-delix-therapeutics-first-investment",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/cameron_olson_lab_ccw.jpeg?h=c673cd1c&itok=akFyWePN",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-reflections-inaugural-triage-innovation-forum",
    "campus": "davis",
    "title": "Reflections on the Inaugural TRIage Innovation Forum",
    "summary": "Andrew Brown of UC Davis Health Ventures shares his thoughts on the creation and launch of the TRIage Innovation Forum—an engaging, rapid-pitch platform that helps researchers present their work in three minutes and receive tailored guidance, resources and connections to accelerate the translation of their innovations into real-world health solutions.",
    "publishedAt": "2025-09-02T16:23:28.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/reflections-inaugural-triage-innovation-forum",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/TRIage%20Pic%201.jpg?h=9c4c0580&itok=BsNJ9CMh",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-dough-data-how-graingeai-reimagining-ingredient-intelligence",
    "campus": "davis",
    "title": "From Dough to Data: How Grainge.ai is Reimagining Ingredient Intelligence",
    "summary": "Grainge.ai, a UC Davis–born startup, is transforming food manufacturing by using AI-driven ingredient intelligence to predict how grains, starches and other ingredients behave in formulations, helping companies innovate more efficiently and sustainably.",
    "publishedAt": "2025-08-18T21:19:43.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/dough-data-how-graingeai-reimagining-ingredient-intelligence",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Screenshot%202025-08-18%20150316.png?h=1fdb4153&itok=kI5ywWph",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-uc-davis-sees-jump-records-invention-driven-health-innovation",
    "campus": "davis",
    "title": "UC Davis Sees Jump in Records of Invention, Driven by Health Innovation",
    "summary": "UC Davis saw a 34% increase in records of invention in FY 2025, driven largely by health-related innovations and first-time contributors, reflecting a growing culture of commercialization and cross-campus collaboration led by the Innovation and Economic Development Office.",
    "publishedAt": "2025-08-04T19:56:16.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-sees-jump-records-invention-driven-health-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/2025-05-22_Avantika%20Gokulnatha_resize.jpg?h=9855f42d&itok=2Wuomug3",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-first-students-move-aggie-square",
    "campus": "davis",
    "title": "First Students Move Into Aggie Square",
    "summary": "UC Davis welcomed residents to Anova Aggie Square, the first student housing ever offered on the Sacramento campus. Anova Aggie Square is a smart residential complex that is now home to students from the UC Davis School of Medicine, the Betty Irene Moore School of Nursing at UC Davis and other graduate programs.",
    "publishedAt": "2025-07-17T16:14:54.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/first-students-move-aggie-square",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/anova-aggie-square-move-in-2025-2000px.jpg?h=c673cd1c&itok=mw0g0UJG",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "riverside-uc-riverside-launches-online-mba-program",
    "campus": "riverside",
    "title": "UC Riverside launches online MBA program",
    "summary": "UC Riverside is launching a fully online Master of Business Administration program this fall, opening the door for students across California, the nation, and around the world to earn a University of California MBA degree remotely while continuing their careers and personal responsibilities.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/05/21/uc-riverside-launches-online-mba-program",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-05/biz-header-960.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-reclaiming-context-creative-works",
    "campus": "riverside",
    "title": "Reclaiming the context of creative works",
    "summary": "New research led by a UC Riverside professor has developed an AI tool that compensates for the shifting genre perceptions that impact how creative works are understood, evaluated, and even discovered.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/04/22/reclaiming-context-creative-works",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-04/960-gettyimages-2264305709-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-ucr-report-urges-broadband-be-state-utility",
    "campus": "riverside",
    "title": "UCR report urges broadband to be a state utility",
    "summary": "California should regulate broadband internet providers like public utilities — imposing rate controls, universal access requirements, and reliability standards to ensure every resident has affordable, high-speed internet access, according to a new UC Riverside public policy report.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/02/12/ucr-report-urges-broadband-be-state-utility",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-02/960-gettyimages-2231090399.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-tangos-sweet-legacy-lives",
    "campus": "riverside",
    "title": "Tango’s sweet legacy lives on",
    "summary": "The UCR-developed Tango mandarin has established itself as a symbol of innovation and sustainability in the global citrus market, generating more than $70 million in cumulative economic value for the university.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/01/15/tangos-sweet-legacy-lives",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-01/960-2025-11-05_tango_004.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-slower-company-acquisition-pace-can-boost-corporate-values",
    "campus": "riverside",
    "title": "Slower company acquisition pace can boost corporate values",
    "summary": "Expanding the time between company acquisitions improves the integration of the new assets and increases corporate values, study finds.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/12/08/slower-company-acquisition-pace-can-boost-corporate-values",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-12/960-gettyimages-147205360.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-shopping-two-stressful",
    "campus": "riverside",
    "title": "Shopping for two is stressful",
    "summary": "A study co-authored by a UCR business professor finds that shopping for goods or services that you will share is significantly more stressful than shopping for yourself or for something to be given to another person.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/12/02/shopping-two-stressful",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-12/960-stressed-shopper.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-study-finds-lower-emissions-higher-ethanol-gasoline",
    "campus": "riverside",
    "title": "Study finds lower emissions from higher-ethanol gasoline",
    "summary": "Landmark UC Riverside vehicle emissions study allows California to move forward with less costly and less polluting gasoline blend.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/11/25/study-finds-lower-emissions-higher-ethanol-gasoline",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-11/960-gettyimages-188115695-1_0.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-study-finds-moral-costs-over-pricing-essentials",
    "campus": "riverside",
    "title": "Study finds moral costs in over-pricing for essentials",
    "summary": "A study led by UC Riverside School of Business professor Margaret C. Campbell found that when companies hike prices on essentials like food, medicine, or medical devices, the financial rewards may be immediate—but the reputational damage may linger and ultimately cost more in the long run.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/11/03/study-finds-moral-costs-over-pricing-essentials",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-11/960-ex-gettyimages-1793165463-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-private-equity-takes-airports-new-heights",
    "campus": "riverside",
    "title": "Private equity takes airports to new heights",
    "summary": "Equity investors improved airport operating and customer service, finds a global study that spanned two decades and four continents.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/10/13/private-equity-takes-airports-new-heights",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-10/madrid-airport.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-farm-conservation-economical-path-save-river-water",
    "campus": "riverside",
    "title": "Farm conservation is an economical path to save river water",
    "summary": "The most cost-effective way to conserve the dwindling waters of the Colorado River may not come from building new reservoirs, canals, or wells, but from changing how water is used on farms that consume most of it.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/09/29/farm-conservation-economical-path-save-river-water",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-09/960-gettyimages-90285343.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-ucr-computer-scientists-boost-us-cybersecurity",
    "campus": "riverside",
    "title": "UCR computer scientists boost US cybersecurity",
    "summary": "UCR computer scientists are developing tools to expose hidden cybersecurity vulnerabilities, protect private data, and strengthen the digital defenses that safeguard everything from personal communications to national infrastructure.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/09/18/ucr-computer-scientists-boost-us-cybersecurity",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-09/960-gettyimages-2174551157.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-report-inland-empire-warehouse-workers-make-gains-through-collective-action",
    "campus": "riverside",
    "title": "Report: Inland Empire warehouse workers make gains through collective action",
    "summary": "In “State of the Unions: California Labor in 2024,” UCR researchers offer details on the growth, salaries, ethnicities, and ongoing struggles of warehouse workers in Riverside and San Bernardino counties",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/09/08/report-inland-empire-warehouse-workers-make-gains-through-collective-action",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2018-09/warehouse.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-nostalgia-asset-company-acquisitions",
    "campus": "riverside",
    "title": "Nostalgia is an asset in company acquisitions",
    "summary": "A study by UCR School of Business scholars found that nostalgia serves as a comforting and stabilizing force during company acquisition periods when employees feel vulnerable, fear losing their jobs, status, or advancement opportunities, and are thus inclined to send out résumés.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/08/20/nostalgia-asset-company-acquisitions",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-10/gettyimages-2238047024.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-groundwater-depletion-sinks-home-prices-californias-central-valley",
    "campus": "riverside",
    "title": "Groundwater depletion sinks home prices in California's Central Valley",
    "summary": "UC Riverside study has found that subsidence from excessive groundwater pumping in California's Central Valley reduced home values between 2.4% and 5.8% or between $6,689 and $16,165 per home. These costs totaled $1.87 billion in aggregate housing value lost, the study estimated.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/07/31/groundwater-depletion-sinks-home-prices-californias-central-valley",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-07/960-gettyimages-2208627482-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-school-business-joins-council-global-business-schools",
    "campus": "riverside",
    "title": "School of Business joins council of global business schools",
    "summary": "UC Riverside’s School of Business has been accepted into the Graduate Management Admission Council, or GMAC, a prestigious global association of leading graduate business schools.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/07/17/school-business-joins-council-global-business-schools",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-07/960-2024-10-18_business_ribbon_cutting_139-copy_0_0.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-uc-riverside-scholar-reimagines-student-engagement",
    "campus": "riverside",
    "title": "UC Riverside scholar reimagines student engagement",
    "summary": "The \"Carry the Class\" teaching method helps college students master concepts while fostering a sense of ownership through more meaningful social interactions among students and faculty, which creates a sense of community and shared purpose.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/07/07/uc-riverside-scholar-reimagines-student-engagement",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-07/960-header-kyle-ingram.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-state-workers-report-addresses-ev-transition",
    "campus": "riverside",
    "title": "State of Workers report addresses EV transition",
    "summary": "Today at the State of Workers in the Inland Empire report release, UC Riverside investigators presented recent statistics on labor market demographics, wages, cost of living, and worker training needs to adapt to changing conditions and emerging technologies such as electric vehicles, or EVs.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/06/10/state-workers-report-addresses-ev-transition",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-06/gettyimages-1406501364_1.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-ucr-launches-study-ship-emissions-socal-coast",
    "campus": "riverside",
    "title": "UCR launches study of ship emissions off SoCal coast",
    "summary": "A team of UC Riverside environmental engineers are embarking on a $3.5 million study of air pollution from massive oceangoing vessels that frequent the ports of Los Angeles and Long Beach—one of the region’s largest sources of toxic air pollution.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/06/02/ucr-launches-study-ship-emissions-socal-coast",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-06/960-gettyimages-1297687827.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-it-good-know-how-much-your-co-workers-make",
    "campus": "riverside",
    "title": "Is it good to know how much your co-workers make?",
    "summary": "Many companies keep employee pay shrouded in secrecy while other employers make such information known to their workers. So, what are the impacts of compensation transparency?",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/04/07/it-good-know-how-much-your-co-workers-make",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-04/960-gettyimages-1258125025-copy-2_1.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "sf-scientists-create-cancer-fighting-immune-cells-right-body",
    "campus": "sf",
    "title": "Scientists Create Cancer-Fighting Immune Cells Right in the Body",
    "summary": "Scientists Create Cancer-Fighting Immune Cells Right in the Body",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/scientists-create-cancer-fighting-immune-cells-right-body",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-molecular-garbage-tumors-makes-easy-target-antibody-drugs",
    "campus": "sf",
    "title": "Molecular Garbage on Tumors Makes Easy Target for Antibody Drugs",
    "summary": "Cancer cells can ‘barf’ proteins onto their cell surface. That may create new targets for immunotherapies",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/molecular-garbage-tumors-makes-easy-target-antibody-drugs",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-ge-healthcare-ucsf-health-form-10-year-imaging-collaboration",
    "campus": "sf",
    "title": "GE HealthCare, UCSF Health form 10-year imaging collaboration",
    "summary": "GE HealthCare has entered a 10-year Care Alliance with UCSF Health aimed at expanding imaging capabilities and supporting clinical operations across the health system.",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ge-healthcare-ucsf-health-form-10-year-imaging-collaboration",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-tissue-repair-slows-old-age-these-proteins-speed-it-back",
    "campus": "sf",
    "title": "Tissue Repair Slows in Old Age. These Proteins Speed It Back Up",
    "summary": "Tissue Repair Slows in Old Age. These Proteins Speed It Back Up",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/tissue-repair-slows-old-age-these-proteins-speed-it-back",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-tahoe-therapeutics-arc-institute-and-biohub-partner-generate-largest-perturbation",
    "campus": "sf",
    "title": "Tahoe Therapeutics, Arc Institute, and Biohub Partner to Generate the Largest Perturbation Dataset for Virtual Cell Models",
    "summary": "Tahoe Therapeutics, Arc Institute, and Biohub Partner to Generate the Largest Perturbation Dataset for Virtual Cell Models",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/tahoe-therapeutics-arc-institute-and-biohub-partner-generate-largest-perturbation",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-jj-google-venture-arms",
    "campus": "sf",
    "title": "J&J, Google venture arms line up to back protein degradation biotech EpiBiologics' $107M series B",
    "summary": "Protein degradation biotech EpiBiologics has brought in $107 million in a star-studded series B round headed up by Johnson & Johnson's and Google's respective venture arms.",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/jj-google-venture-arms",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  }
];
