// AUTO-GENERATED by `vp run build-news-data`. Do not edit by hand.
// Source: data/news/*.json — last refresh: 2026-05-07T01:18:25.168Z
// Run `vp run crawl:news` followed by `vp run build-news-data` to refresh.
import type { NewsItem } from "./news.ts";

export const NEWS: NewsItem[] = [
  {
    id: "la-ucla-anderson-school-management-launches-minors-real-estate-and-sports-leadership-and-management",
    campus: "la",
    title:
      "UCLA Anderson School of Management Launches Minors in Real Estate and Sports Leadership and Management",
    summary:
      "The two new minors expand the school’s undergraduate offerings, which include minors in Accounting and Entrepreneurship",
    publishedAt: "2026-04-15T12:00:00.000Z",
    sourceUrl:
      "https://www.anderson.ucla.edu/news-and-events/ucla-anderson-school-management-launches-minors-real-estate-and-sports-leadership-and-management",
    imageUrl:
      "https://www.anderson.ucla.edu/sites/default/files/styles/social_og/public/image/2026-04/20260415-campus-drone-card.jpg.jpeg?itok=QzAacVws",
    sourceHost: "www.anderson.ucla.edu",
  },
  {
    id: "berkeley-meet-debasish-behera-the-founder-making-global-payment-more-accessible",
    campus: "berkeley",
    title: "Meet Debasish Behera, the Founder Making Global Payment more Accessible",
    summary:
      "Debasish Behera, originally a student from India, joined the SCET community after participating in the Startup Semester at Berkeley in the spring of 2025. Since then, he has immersed himself…",
    publishedAt: "2026-05-06T17:57:00.000Z",
    sourceUrl:
      "https://scet.berkeley.edu/meet-debasish-behera-the-founder-making-global-payment-more-accessible/",
    imageUrl: "https://begin.berkeley.edu/wp-content/uploads/2026/05/debasish-683x1024.png",
    sourceHost: "scet.berkeley.edu",
  },
  {
    id: "berkeley-new-ai-entrepreneurship-course-is-a-hands-on-startup-accelerator-for-mba-founders",
    campus: "berkeley",
    title: "New AI Entrepreneurship course is a hands-on startup accelerator for MBA founders",
    summary:
      "Alex Zekoff, MBA 17, who co-teaches AI and Entrepreneurship with Professor Omri Even-Tov, posing a question about fundraising to the class. Photo: Noah Berger On a recent Thursday afternoon Alex…",
    publishedAt: "2026-05-06T16:01:00.000Z",
    sourceUrl:
      "https://newsroom.haas.berkeley.edu/new-ai-entrepreneurship-course-is-a-hands-on-startup-accelerator-for-mba-founders/",
    imageUrl: "https://begin.berkeley.edu/wp-content/uploads/2026/05/bkc_580a-768x512.jpg",
    sourceHost: "newsroom.haas.berkeley.edu",
  },
  {
    id: "santabarbara-beacon-photonics-first-industry-member-ucsb-oasis",
    campus: "santabarbara",
    title: "Beacon Photonics First Industry Member at UCSB OASIS",
    summary:
      "OASIS is built to accelerate discovery and move ideas from lab to application, connecting companies directly with UCSB’s research expertise and shared-use facilities.",
    publishedAt: "2026-05-04T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/beacon-photonics-first-industry-member-ucsb-oasis",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-05/BEACON_OASIS.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "irvine-born-in-california-2026",
    campus: "irvine",
    title: "The Pipeline",
    summary: "What does it take to make a UC idea matter in the real world?",
    publishedAt: "2026-04-29T16:30:40.000Z",
    sourceUrl: "https://innovation.uci.edu/news/born-in-california-2026/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2023/01/Neried-biomaterials1.jpg",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "santabarbara-new-venture-competition-finalists-2026",
    campus: "santabarbara",
    title: "New Venture Competition Finalists 2026",
    summary: "New Venture Competition Finalists of 2026",
    publishedAt: "2026-04-29T07:00:00.000Z",
    sourceUrl: "https://innovation.ucsb.edu/blog/news/new-venture-competition-finalists-2026",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-04/Untitled%20design_0.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "sf-qa-nicholas-hertz-president-ceo-montara-therapeutics",
    campus: "sf",
    title: "Q&A with Nicholas Hertz, President & CEO of Montara Therapeutics",
    summary: "Q&amp;A with Nicholas Hertz, President &amp; CEO of Montara Therapeutics",
    publishedAt: "2026-04-29T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/qa-nicholas-hertz-president-ceo-montara-therapeutics",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-breakthrough-device-designation-aidabreastr-early-stage-invasive-breast-cancer-assay",
    campus: "sf",
    title:
      "Breakthrough Device Designation for AidaBREAST® - Early-Stage Invasive Breast Cancer Assay",
    summary:
      "Breakthrough Device Designation for AidaBREAST® - Early-Stage Invasive Breast Cancer Assay",
    publishedAt: "2026-04-29T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/breakthrough-device-designation-aidabreastr-early-stage-invasive-breast-cancer-assay",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "irvine-ecotune",
    campus: "irvine",
    title: "The Material Question",
    summary: "What if materials weren’t just made, but designed in tune with nature?",
    publishedAt: "2026-04-24T22:38:57.000Z",
    sourceUrl: "https://innovation.uci.edu/news/ecotune/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2026/04/Ecotune-scaled.jpg",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "santabarbara-techtopia-2026-showcases-ucsbs-expanding-innovation-ecosystem",
    campus: "santabarbara",
    title: "TechTopia 2026 Showcases UCSB’s Expanding Innovation Ecosystem",
    summary:
      "At TechTopia 2026, UC Santa Barbara and industry partners emphasized collaboration and introduced OASIS, a new facility supporting startups as they transition from research to industry.",
    publishedAt: "2026-04-22T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/techtopia-2026-showcases-ucsbs-expanding-innovation-ecosystem",
    imageUrl: "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-04/download.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "sf-ucb-acquire-neurona-therapeutics-advancing-its-innovative-leadership-epilepsy-through",
    campus: "sf",
    title:
      "UCB to acquire Neurona Therapeutics, advancing its innovative leadership in epilepsy through regenerative science",
    summary:
      "UCB to acquire Neurona Therapeutics, advancing its innovative leadership in epilepsy through regenerative science",
    publishedAt: "2026-04-17T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/ucb-acquire-neurona-therapeutics-advancing-its-innovative-leadership-epilepsy-through",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "irvine-sounddose",
    campus: "irvine",
    title: "The Blind Spot in Modern Radiation Therapy",
    summary: "How UC Irvine startup SoundDose is tackling one of cancer care’s biggest unknowns",
    publishedAt: "2026-04-15T19:13:47.000Z",
    sourceUrl: "https://innovation.uci.edu/news/sounddose/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2026/04/Sound-Dose.jpg",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "davis-uc-davis-launches-aggie-venture-accelerator-advance-early-stage-life-science-innovation",
    campus: "davis",
    title:
      "UC Davis Launches Aggie Venture Accelerator to Advance Early Stage Life Science Innovation",
    summary:
      "The UC Davis Innovation and Economic Development Office has launched the Aggie Venture Accelerator, an initiative designed to support early stage startups developing solutions at the intersection of life science, food and health.",
    publishedAt: "2026-04-13T09:15:36-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-launches-aggie-venture-accelerator-advance-early-stage-life-science-innovation",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_1788_reduced.jpg?h=37bd9af6&itok=3XXTuw-j",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-aggie-square-partners-release-first-community-benefits-progress-report-highlighting-early",
    campus: "davis",
    title:
      "Aggie Square Partners Release First Community Benefits Progress Report Highlighting Early Impact",
    summary:
      "The first Aggie Square Community Benefits Partnership Agreement (CBPA) Annual Progress Report has been released by UC Davis, the City of Sacramento and Wexford Science & Technology, documenting significant progress towards meeting many of the goals outlined in the CBPA.",
    publishedAt: "2026-04-02T15:40:20-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/aggie-square-partners-release-first-community-benefits-progress-report-highlighting-early",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_6025.jpg?h=4997dc06&itok=8Y1gDdgI",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "irvine-mifti",
    campus: "irvine",
    title: "The $40 Trillion Question",
    summary: "Can MIFTI, a scrappy UC Irvine-based startup, outpace billion-dollar fusion giants?",
    publishedAt: "2026-03-30T22:53:07.000Z",
    sourceUrl: "https://innovation.uci.edu/news/mifti/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2026/03/MIFTI-1.jpg",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "davis-uc-davis-health-ventures-appoints-troels-adrian-strengthen-industry-partnerships-and-advance",
    campus: "davis",
    title:
      "UC Davis Health Ventures Appoints Troels Adrian to Strengthen Industry Partnerships and Advance the UC Davis Health Clinical Test Bed",
    summary:
      "UC Davis Health Ventures, part of the Innovation and Economic Development Office at UC Davis, today announced the appointment of Troels Adrian as Director of Industry Engagement.",
    publishedAt: "2026-03-23T08:18:26-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-health-ventures-appoints-troels-adrian-strengthen-industry-partnerships-and-advance",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Troels%20Adrian%20COLOR.jpg?h=d73b4fec&itok=cVMoxhzz",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-food-health-angels-network-launches-accelerate-science-driven-food-and-health-innovation",
    campus: "davis",
    title:
      "Food & Health Angels Network Launches to Accelerate Science-Driven Food and Health Innovation",
    summary:
      "Introducing the Food & Health Angels Network, a groundbreaking initiative launched to accelerate science-driven innovations in food and health, addressing the pressing issue of metabolic disease.",
    publishedAt: "2026-03-19T09:15:08-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/food-health-angels-network-launches-accelerate-science-driven-food-and-health-innovation",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/real-food-pyramid-arrangement.jpg?h=5313cdcb&itok=vL82Pgy9",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "sd-a-uc-san-diego-tool-teaching-code-to-25-million-is-even-more-critical-in-age-of-ai",
    campus: "sd",
    title: "A UC San Diego Tool Teaching Code to 25 Million is Even More Critical in Age of AI",
    summary:
      "When generative AI began writing code with uncanny fluency, it sparked a question: If a chatbot can build software, do people still need to learn to code? Professor of Cognitive Science Philip Guo says absolutely. Understanding code is now more important than ever because AI can get it wrong.",
    publishedAt: "2026-03-19T07:00:00.000Z",
    sourceUrl:
      "https://today.ucsd.edu/story/a-uc-san-diego-tool-teaching-code-to-25-million-is-even-more-critical-in-age-of-ai",
    imageUrl: "https://today.ucsd.edu/teaser_uploads/_social/iStock-2175838440%282%29%281%29.jpg",
    sourceHost: "today.ucsd.edu",
  },
  {
    id: "sf-ucsf-receives-824m-nih-funding-driving-medical-breakthroughs",
    campus: "sf",
    title: "UCSF Receives $824M in NIH Funding, Driving Medical Breakthroughs",
    summary: "UCSF Receives $824M in NIH Funding, Driving Medical Breakthroughs -",
    publishedAt: "2026-03-13T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/ucsf-receives-824m-nih-funding-driving-medical-breakthroughs",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-vs3-medical-announces-first-patients-enrolled-first-human-study-novel-neurovascular",
    campus: "sf",
    title:
      "VS3 Medical Announces First Patients Enrolled in First-in-Human Study of Novel Neurovascular Implant to Address Symptomatic Venous Sinus Stenosis",
    summary:
      "VS3 Medical Announces First Patients Enrolled in First-in-Human Study of Novel Neurovascular Implant to Address Symptomatic Venous Sinus Stenosis",
    publishedAt: "2026-03-10T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/vs3-medical-announces-first-patients-enrolled-first-human-study-novel-neurovascular",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sd-americans-dont-just-fear-driverless-cars-will-crashthey-fear-mass-job-loss",
    campus: "sd",
    title: "Americans Don’t Just Fear Driverless Cars Will Crash",
    summary:
      "While much of the public debate about self-driving cars focuses on safety, a new national study from the UC San Diego reveals many Americans’ doubts about driverless focused on the technology’s economic ripple effects — especially job losses in driving and delivery work.  ",
    publishedAt: "2026-03-05T08:00:00.000Z",
    sourceUrl:
      "https://today.ucsd.edu/story/americans-dont-just-fear-driverless-cars-will-crashthey-fear-mass-job-loss",
    imageUrl: "https://today.ucsd.edu/teaser_uploads/_social/iStock-2204573658%281%29%282%29.jpg",
    sourceHost: "today.ucsd.edu",
  },
  {
    id: "irvine-neuroqure",
    campus: "irvine",
    title: "A New Signal for Autism",
    summary: "How UC Irvine research and a father’s story are changing the timeline of care",
    publishedAt: "2026-02-27T20:40:15.000Z",
    sourceUrl: "https://innovation.uci.edu/news/neuroqure/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2026/02/NeuroQure-2.png",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "sd-why-tariff-uncertainty-may-hurt-more-than-tariffs",
    campus: "sd",
    title: "Why Tariff Uncertainty May Hurt More Than Tariffs",
    summary:
      "Q&A with School of Global Policy and Strategy economist on what uncertainty means for businesses, how volatility affects global credibility and what policy choices lie ahead.",
    publishedAt: "2026-02-26T08:00:00.000Z",
    sourceUrl: "https://today.ucsd.edu/story/why-tariff-uncertainty-may-hurt-more-than-tariffs",
    imageUrl:
      "https://today.ucsd.edu/teaser_uploads/_social/Economic-Uncertainty-concept-image-by-iStock_DNY59-1069395454-crop1200.jpg",
    sourceHost: "today.ucsd.edu",
  },
  {
    id: "irvine-eira-bio",
    campus: "irvine",
    title: "Is This the Breakthrough Drug Development We’ve Been Waiting For?",
    summary:
      "Eira Bio is targeting membrane proteins long considered unreachable by antibody drugs.",
    publishedAt: "2026-02-17T18:32:41.000Z",
    sourceUrl: "https://innovation.uci.edu/news/eira-bio/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2026/02/Eira-Bio-1.png",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "irvine-vena-vitals",
    campus: "irvine",
    title: "Can Wearable Tech Finally Get Blood Pressure Right?",
    summary:
      "Forget the cuff. Vena Vitals’ sticker-like sensor aims to deliver ICU-level data without ever breaking the skin.",
    publishedAt: "2026-02-17T17:42:05.000Z",
    sourceUrl: "https://innovation.uci.edu/news/vena-vitals/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2026/02/Vena-Vitals-1.jpg",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "davis-uc-davis-highlights-translational-breakthroughs-and-startups-8th-annual-biotech-innovation",
    campus: "davis",
    title:
      "UC Davis Highlights Translational Breakthroughs and Startups at the 8th Annual Biotech Innovation Gallery",
    summary:
      "UC Davis showcased groundbreaking translational research and innovative biotech startups at the 8th Annual Biotech Innovation Gallery in San Francisco. Hosted by the UC Davis Innovation and Economic Development Office, the event brought in over 330 attendees to connect with and explore potential partnerships with researchers and startup founders, aligning with the J.P. Morgan Healthcare Conference",
    publishedAt: "2026-02-10T08:51:50-08:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-highlights-translational-breakthroughs-and-startups-8th-annual-biotech-innovation",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/David%20Segal_BIG.jpg?h=9c4c0580&itok=cZtQYKZp",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "irvine-summit-tech",
    campus: "irvine",
    title: "When Reality is the Canvas",
    summary: "How Aditi Majumder is Building the Ultimate 3D Experience",
    publishedAt: "2026-01-22T16:00:01.000Z",
    sourceUrl: "https://innovation.uci.edu/news/summit-tech/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2025/12/STL-image-1.png",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "sd-why-some-messages-are-more-convincing-than-others",
    campus: "sd",
    title: "Why Some Messages Are More Convincing Than Others",
    summary:
      "What kinds of marketing messages are effective — and what makes people believe certain political slogans more than others? New research from the University of California San Diego Rady School of Management explains. ",
    publishedAt: "2026-01-22T08:00:00.000Z",
    sourceUrl: "https://today.ucsd.edu/story/why-some-messages-are-more-convincing-than-others",
    imageUrl: "https://today.ucsd.edu/teaser_uploads/_social/iStock-2231577862%281%29%283%29.jpg",
    sourceHost: "today.ucsd.edu",
  },
  {
    id: "sd-from-wharton-to-womens-fashion-designer-stuart-weitzman-inspires-rady-students",
    campus: "sd",
    title: "From Wharton to Women’s Fashion: Designer Stuart Weitzman Inspires Rady Students",
    summary:
      "Men buy around one to two pairs of shoes a year. Women purchase around 13 pairs annually. This was the data point that inspired Stuart Weitzman to create a business centered around women's footwear. Weitzman recently share his story with students at the Rady School of Management. ",
    publishedAt: "2026-01-15T08:00:00.000Z",
    sourceUrl:
      "https://today.ucsd.edu/story/from-wharton-to-womens-fashion-designer-stuart-weitzman-inspires-rady-students",
    imageUrl: "https://today.ucsd.edu/teaser_uploads/_social/DSC07669%281%29%281%29.jpg",
    sourceHost: "today.ucsd.edu",
  },
  {
    id: "sf-tahoe-therapeutics-and-alloy-therapeutics-form-joint-venture-and-develop-first-class",
    campus: "sf",
    title:
      "Tahoe Therapeutics and Alloy Therapeutics to Form Joint Venture and Develop First-in-Class Antibody-Drug Conjugates for Hard-to-Treat Cancers",
    summary:
      "Tahoe Therapeutics and Alloy Therapeutics to Form Joint Venture and Develop First-in-Class Antibody-Drug Conjugates for Hard-to-Treat Cancers",
    publishedAt: "2026-01-14T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/tahoe-therapeutics-and-alloy-therapeutics-form-joint-venture-and-develop-first-class",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "santabarbara-professor-phillip-christopher-and-stephen-wilson-named-among-worlds-most-influential",
    campus: "santabarbara",
    title:
      "Professor Phillip Christopher and Stephen Wilson Named Among the World’s Most Influential Researchers",
    summary:
      "Chemical Engineering Professor Phillip Christopher and Materials Professor Stephen Wilson have been recognized among the world’s most influential scientists.",
    publishedAt: "2026-01-13T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/professor-phillip-christopher-and-stephen-wilson-named-among-worlds-most-influential",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/2025_highly_cited.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-ucsb-associate-professor-chemistry-and-biochemistry-grace-han-named-moore-inventor-fellow",
    campus: "santabarbara",
    title:
      "UCSB Associate Professor of Chemistry and Biochemistry Grace Han named Moore Inventor Fellow",
    summary:
      "UC Santa Barbara Associate Professor of Chemistry and Biochemistry Grace Han has been named one of five scientist-inventors nationwide to receive a 2025 Moore Inventor Fellowship from the Gordon and Betty Moore Foundation.",
    publishedAt: "2026-01-13T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-associate-professor-chemistry-and-biochemistry-grace-han-named-moore-inventor-fellow",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/Grace-Han_opt.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-ucsb-professor-blumenthals-lab-selected-nsfs-national-quantum-virtual-laboratory",
    campus: "santabarbara",
    title: "UCSB Professor Blumenthal’s Lab Selected for NSF's National Quantum Virtual Laboratory",
    summary:
      "UC Santa Barbara professor Daniel Blumenthal’s lab is part of one of four design teams from around the country selected by the National Science Foundation for its recently launched National Quantum Virtual Laboratory (NVQL).",
    publishedAt: "2026-01-13T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-professor-blumenthals-lab-selected-nsfs-national-quantum-virtual-laboratory",
    imageUrl: "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/blumenthal.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-fda-clears-osteoprober-first-ever-device-indication-measuring-bone-material-strength",
    campus: "santabarbara",
    title:
      "FDA Clears OsteoProbe®: First-Ever Device Indication for Measuring Bone Material Strength",
    summary:
      "UCSB startup Active Life Scientific announced that the U.S. Food and Drug Administration has granted clearance for their OsteoProbe® device. Their BoneScore® procedure offers a direct, minimally-invasive assessment of bone tissue quality.",
    publishedAt: "2026-01-13T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/fda-clears-osteoprober-first-ever-device-indication-measuring-bone-material-strength",
    imageUrl: "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/Group-416.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-ucsb-professor-kevin-plaxco-elected-fellow-national-academy-inventors",
    campus: "santabarbara",
    title: "UCSB Professor Kevin Plaxco Elected Fellow of National Academy of Inventors",
    summary:
      "NAI Fellowship is the highest professional distinction awarded solely to inventors. Their success in translating research into products and services that improve lives.",
    publishedAt: "2026-01-13T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-professor-kevin-plaxco-elected-fellow-national-academy-inventors",
    imageUrl: "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-01/KevinPlaxco.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "sd-calibaja-higher-education-consortium-officially-launches",
    campus: "sd",
    title: "CaliBaja Higher Education Consortium Officially Launches",
    summary:
      "The University of California San Diego is joining a new alliance uniting higher education institutions from California and Baja California, the CaliBaja Higher Education Consortium (CHEC). \n",
    publishedAt: "2025-12-10T08:00:00.000Z",
    sourceUrl:
      "https://today.ucsd.edu/story/calibaja-higher-education-consortium-officially-launches",
    imageUrl: "https://today.ucsd.edu/teaser_uploads/_social/iStock-2227414883%281%29.jpg",
    sourceHost: "today.ucsd.edu",
  },
  {
    id: "sf-montara-therapeutics-announces-development-candidate-first-brainonlytm-enabled-program",
    campus: "sf",
    title:
      "Montara Therapeutics Announces Development Candidate for First BrainOnly™-Enabled Program in TSC-Related Epilepsy and Appoints Chief Business Officer",
    summary:
      "Montara Therapeutics Announces Development Candidate for First BrainOnly™-Enabled Program in TSC-Related Epilepsy and Appoints Chief Business Officer&nbsp;",
    publishedAt: "2025-12-10T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/montara-therapeutics-announces-development-candidate-first-brainonlytm-enabled-program",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-alice-tang-made-forbes-30-under-30-list-science",
    campus: "sf",
    title: "Alice Tang Made the Forbes 30 Under 30 List in Science",
    summary: "Alace Tang achieved the Forbes 30 Under 30 in Science",
    publishedAt: "2025-12-09T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/alice-tang-made-forbes-30-under-30-list-science",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "davis-uc-davis-announces-winners-autumn-2025-science-translation-and-innovative-research-grant",
    campus: "davis",
    title:
      "UC Davis Announces Winners of Autumn 2025 Science Translation and Innovative Research Grant Program",
    summary:
      "The University of California, Davis, has awarded $100,000 through the autumn 2025 cohort of the Science Translation and Innovative Research (STAIR) Grant Program to help scientists advance innovative research with strong commercial potential.",
    publishedAt: "2025-12-08T12:48:03-08:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-announces-winners-autumn-2025-science-translation-and-innovative-research-grant",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Baar_Abhaya.jpg?h=52d3fcb6&itok=7en2k7q-",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "irvine-zeppelin-floods",
    campus: "irvine",
    title: "When the Levee Breaks",
    summary: "What if everyone could plan infrastructure?",
    publishedAt: "2025-12-02T16:00:20.000Z",
    sourceUrl: "https://innovation.uci.edu/news/zeppelin-floods/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2025/11/Zeppelin-Floods.png",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "santabarbara-aeluma-joins-midwest-microelectronics-consortium",
    campus: "santabarbara",
    title: "Aeluma Joins the Midwest Microelectronics Consortium",
    summary:
      "UCSB Professor Jonathan Klamkin’s company, Aeluma, joined the Midwest Microelectronics Consortium to advance its semiconductor photonics technologies for AI, quantum, and defense applications.",
    publishedAt: "2025-12-02T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/aeluma-joins-midwest-microelectronics-consortium",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-12/image%282%29.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-ucsb-graduates-startup-pioneers-soft-robotic-intubation-device",
    campus: "santabarbara",
    title: "UCSB Graduate’s Startup Pioneers Soft Robotic Intubation Device",
    summary:
      "Vine Medical, a UCSB CSNI member founded by recent UCSB Ph.D. graduate Dr. David Haggerty, is developing a soft robotic “vine” device that makes emergency intubation faster, safer, and more reliable than traditional laryngoscopes.",
    publishedAt: "2025-11-20T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-graduates-startup-pioneers-soft-robotic-intubation-device",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-11/Vine%20Medical_square.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-rallio-won-netty-award-best-use-ai-marketing",
    campus: "santabarbara",
    title: "Rallio Won the Netty Award for Best Use of AI in Marketing",
    summary:
      "Rallio, an AI-powered social publishing platform, won the Netty Award for Best Use of AI in Marketing. Rallio’s CEO and Co-Founder, Chuck Goetschel, is a member of the UCSB Innovators Circle.",
    publishedAt: "2025-11-20T08:00:00.000Z",
    sourceUrl: "https://innovation.ucsb.edu/blog/news/rallio-won-netty-award-best-use-ai-marketing",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-11/rallio_netty-awards_cover-image.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-aeluma-inc-wins-2025-leap-award-advanced-materials-innovation",
    campus: "santabarbara",
    title: "Aeluma, Inc. Wins 2025 LEAP Award for Advanced Materials Innovation",
    summary:
      "Aeluma includes the leadership of UCSB Professor Jonathan Klamkin, who serves as CEO and Director, and Professor Steven DenBaars, who sits on the company’s Board of Directors. Aeluma, Inc., a transformative semiconductor company, has received a 2025 LEAP Award.",
    publishedAt: "2025-11-20T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/aeluma-inc-wins-2025-leap-award-advanced-materials-innovation",
    imageUrl: "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-11/Aeluma.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-ucsb-startup-turns-agricultural-waste-fabric-future",
    campus: "santabarbara",
    title: "UCSB Startup Turns Agricultural Waste into the Fabric of the Future",
    summary:
      "The Hurt Co. was founded by Bren School graduates Taylor Heisley-Cook and David Mun. What started as a UCSB thesis project is now helping shift the fashion industry toward more affordable, eco-friendly materials.",
    publishedAt: "2025-11-13T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-startup-turns-agricultural-waste-fabric-future",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-11/output-onlinepngtools%2B%282%29.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-nereid-biomaterials-named-startup-month",
    campus: "santabarbara",
    title: "Nereid Biomaterials Named Startup of the Month",
    summary:
      "Nereid Biomaterials was named Startup of the Month by Comstock's Magazine for developing ocean-degradable materials to reduce marine plastic pollution.",
    publishedAt: "2025-11-13T08:00:00.000Z",
    sourceUrl: "https://innovation.ucsb.edu/blog/news/nereid-biomaterials-named-startup-month",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-11/1125-startup-lead-template.png",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "irvine-elder-wisdom",
    campus: "irvine",
    title: "Can a Digital Human Pass Down a Legacy?",
    summary:
      "Memoirs are static. Lectures are one-way. Books gather dust. What if wisdom talked back?",
    publishedAt: "2025-11-06T23:55:05.000Z",
    sourceUrl: "https://innovation.uci.edu/news/elder-wisdom/",
    imageUrl: "https://innovation.uci.edu/wp-content/uploads/2025/11/Elder-Wisdom-1.png",
    sourceHost: "innovation.uci.edu",
  },
  {
    id: "davis-venture-catalyst-fuels-record-year-uc-davis-innovation-startups",
    campus: "davis",
    title: "Venture Catalyst Fuels Record Year for UC Davis Innovation Startups",
    summary:
      "At Venture Catalyst, part of the UC Davis Innovation and Economic Development Office, we're proud to support the translation of UC Davis research and technology into real-world applications by fostering the development of new ventures. Through strategic collaborations, training and mentorship programs, funding translational research, and proactive outreach, we foster the university’s entrepreneuri",
    publishedAt: "2025-10-30T08:49:44-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/venture-catalyst-fuels-record-year-uc-davis-innovation-startups",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/VC%20Stats.png?h=c673cd1c&itok=x8MxJRRm",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "santabarbara-ucsb-faculty-and-alumni-recognized-times-best-inventions-2025",
    campus: "santabarbara",
    title: "UCSB Faculty and Alumni Recognized in TIME’s Best Inventions of 2025",
    summary:
      "Three Gauchos made TIME’s Best Inventions of 2025, reflecting the university’s ongoing impact in sustainability, technology, and health research.",
    publishedAt: "2025-10-30T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-faculty-and-alumni-recognized-times-best-inventions-2025",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-10/majorana-1-time-inventions.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-ucsb-alum-heather-hochrein-turns-class-project-evmatch",
    campus: "santabarbara",
    title: "UCSB Alum Heather Hochrein Turns Class Project into EVmatch",
    summary:
      "Heather Hochrein founded EVmatch while earning her master’s at UCSB’s Bren School. What began as a class project to improve EV charging access has grown into a company expanding shared charging options for renters and multifamily housing.",
    publishedAt: "2025-10-30T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsb-alum-heather-hochrein-turns-class-project-evmatch",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-10/Hochrein_headshot_2022_square.jpg.jpeg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "davis-discovery-forum-highlights-how-uc-davis-center-glp-1-and-metabolic-health-innovation",
    campus: "davis",
    title:
      "Discovery Forum Highlights How UC Davis Is at the Center of GLP-1 and Metabolic Health Innovation",
    summary:
      "The Discovery Forum showcased UC Davis as a leader in GLP-1 and metabolic health innovation, bringing together researchers, industry experts, and investors to explore how metabolic hormones are reshaping health and nutrition. With cutting-edge research, world-class facilities, and a strong innovation ecosystem, the event was a reminder of UC Davis’ unique ability to translate metabolic science int",
    publishedAt: "2025-10-15T13:10:27-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/discovery-forum-highlights-how-uc-davis-center-glp-1-and-metabolic-health-innovation",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/IMG_5290.jpg?h=5dc9785f&itok=LuFfzZNo",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-uc-davis-healths-ifm-fund-backs-delix-therapeutics-first-investment",
    campus: "davis",
    title: "UC Davis Health’s IFM Fund Backs Delix Therapeutics in First Investment",
    summary:
      "UC Davis Health Ventures, part of the Innovation and Economic Development Office (IEDO) at the University of California, Davis, today announced the first investment from its Investing in the Future of Medicine (IFM) Fund, backing Delix Therapeutics.",
    publishedAt: "2025-10-02T09:10:43-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-healths-ifm-fund-backs-delix-therapeutics-first-investment",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/cameron_olson_lab_ccw.jpeg?h=c673cd1c&itok=akFyWePN",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-reflections-inaugural-triage-innovation-forum",
    campus: "davis",
    title: "Reflections on the Inaugural TRIage Innovation Forum",
    summary:
      "Andrew Brown of UC Davis Health Ventures shares his thoughts on the creation and launch of the TRIage Innovation Forum—an engaging, rapid-pitch platform that helps researchers present their work in three minutes and receive tailored guidance, resources and connections to accelerate the translation of their innovations into real-world health solutions.",
    publishedAt: "2025-09-02T09:23:28-07:00",
    sourceUrl: "https://iedo.ucdavis.edu/news/reflections-inaugural-triage-innovation-forum",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/TRIage%20Pic%201.jpg?h=9c4c0580&itok=BsNJ9CMh",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-dough-data-how-graingeai-reimagining-ingredient-intelligence",
    campus: "davis",
    title: "From Dough to Data: How Grainge.ai is Reimagining Ingredient Intelligence",
    summary:
      "Grainge.ai, a UC Davis–born startup, is transforming food manufacturing by using AI-driven ingredient intelligence to predict how grains, starches and other ingredients behave in formulations, helping companies innovate more efficiently and sustainably.",
    publishedAt: "2025-08-18T14:19:43-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/dough-data-how-graingeai-reimagining-ingredient-intelligence",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Screenshot%202025-08-18%20150316.png?h=1fdb4153&itok=kI5ywWph",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-uc-davis-sees-jump-records-invention-driven-health-innovation",
    campus: "davis",
    title: "UC Davis Sees Jump in Records of Invention, Driven by Health Innovation",
    summary:
      "UC Davis saw a 34% increase in records of invention in FY 2025, driven largely by health-related innovations and first-time contributors, reflecting a growing culture of commercialization and cross-campus collaboration led by the Innovation and Economic Development Office.",
    publishedAt: "2025-08-04T12:56:16-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-sees-jump-records-invention-driven-health-innovation",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/2025-05-22_Avantika%20Gokulnatha_resize.jpg?h=9855f42d&itok=2Wuomug3",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-first-students-move-aggie-square",
    campus: "davis",
    title: "First Students Move Into Aggie Square",
    summary:
      "UC Davis welcomed residents to Anova Aggie Square, the first student housing ever offered on the Sacramento campus. Anova Aggie Square is a smart residential complex that is now home to students from the UC Davis School of Medicine, the Betty Irene Moore School of Nursing at UC Davis and other graduate programs.",
    publishedAt: "2025-07-17T09:14:54-07:00",
    sourceUrl: "https://iedo.ucdavis.edu/news/first-students-move-aggie-square",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/anova-aggie-square-move-in-2025-2000px.jpg?h=c673cd1c&itok=mw0g0UJG",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-prototype-purpose-conversation-expert-iep-founder-antoinette-banks",
    campus: "davis",
    title: "From Prototype to Purpose: A Conversation with Expert IEP Founder Antoinette Banks",
    summary:
      "Antoinette Banks transformed a mother’s struggle for her daughter’s education into Expert IEP, a platform that combines neuroscience, lived experience, and tech to empower families and reform outdated IEP systems.",
    publishedAt: "2025-07-01T17:06:24-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/prototype-purpose-conversation-expert-iep-founder-antoinette-banks",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Banks_1280x720.jpg?h=c673cd1c&itok=MuO-DDjA",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "santabarbara-ucsbs-technology-incubator-celebrates-10-years-campus",
    campus: "santabarbara",
    title: "UCSB’s Technology Incubator celebrates 10 years on campus",
    summary:
      'In 2015, the California NanoSystems Institute (CNSI) at UC Santa Barbara established the Technology Incubator in Elings Hall to support startup companies stemming from technologies developed on campus. Now in its 10th anniversary year, the incubator has become “a humming innovation ecosystem".',
    publishedAt: "2025-06-23T07:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/ucsbs-technology-incubator-celebrates-10-years-campus",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-06/CNSI%20Incubator%20Wall.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "davis-uc-davis-partners-global-accelerator-and-venture-capital-firm-drive-life-sciences-innovation",
    campus: "davis",
    title:
      "UC Davis Partners with Global Accelerator and Venture Capital Firm to Drive Life Sciences Innovation and Expand Aggie Square's Impact",
    summary:
      "UC Davis strengthens its global life sciences ecosystem with strategic partnerships with FLANN Inc. and HM Venture Partners, aiming to attract international biotech startups to Aggie Square and accelerate the commercialization of groundbreaking healthcare innovations.",
    publishedAt: "2025-05-14T14:21:15-07:00",
    sourceUrl:
      "https://iedo.ucdavis.edu/news/uc-davis-partners-global-accelerator-and-venture-capital-firm-drive-life-sciences-innovation",
    imageUrl:
      "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/20250502-aggie-square-art-7495-reduced.jpg?h=f728280d&itok=9pBcK_hJ",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "santabarbara-next-energy-upgrades-pilot-production-line-opv-windows",
    campus: "santabarbara",
    title: "Next Energy upgrades pilot production line on OPV windows",
    summary:
      "Next Energy Technologies, a Goleta-based organic photovoltaic (OPV) technology company and UCSB CNSI Incubator Alum, has upgraded its pilot production line.",
    publishedAt: "2025-03-06T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/next-energy-upgrades-pilot-production-line-opv-windows",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-03/NEXT_Energy_40_x_60_OPV_Pilot_Production.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-palisades-fire-serves-unfortunate-test-case-plan-b-power-system-coming-soon-santa-barbara",
    campus: "santabarbara",
    title:
      "Palisades Fire Serves as ‘Unfortunate Test Case’ for Plan-B Power System Coming Soon to Santa Barbara",
    summary:
      "Unite to Light, James S. Bower Foundation Partner with Dragon Q Energy to Install 10 PowerPoles Across S.B. County.",
    publishedAt: "2025-01-31T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/palisades-fire-serves-unfortunate-test-case-plan-b-power-system-coming-soon-santa-barbara",
    imageUrl:
      "https://innovation.ucsb.edu/sites/default/files/images/blog/2025-01/DragonQ%20PowerPole.jpg",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "santabarbara-pseudolithic-inc-raises-6m-seed-funding-revolutionize-wireless-chips-proprietary-chiplet",
    campus: "santabarbara",
    title:
      "PseudolithIC Inc. Raises $6M in Seed Funding to Revolutionize Wireless Chips with Proprietary Chiplet Heterogeneous Integration Technology.",
    summary:
      "PseudolithIC Inc., an innovative leader in RF (radio frequency) chipset products, today announced it has successfully raised $6 million in a seed funding round. The round was led by Entrada Ventures, with additional investments from Foothill Ventures and Uncork Capital.",
    publishedAt: "2025-01-28T08:00:00.000Z",
    sourceUrl:
      "https://innovation.ucsb.edu/blog/news/pseudolithic-inc-raises-6m-seed-funding-revolutionize-wireless-chips-proprietary-chiplet",
    sourceHost: "innovation.ucsb.edu",
  },
  {
    id: "davis-18",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/18",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-19",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/19",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-20",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/20",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-21",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/21",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-22",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/22",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-23",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/23",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-24",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/24",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "davis-17",
    campus: "davis",
    title: "Innovation and Economic Development Office",
    summary: "",
    publishedAt: "",
    sourceUrl: "https://iedo.ucdavis.edu/news/17",
    sourceHost: "iedo.ucdavis.edu",
  },
  {
    id: "riverside-reclaiming-context-creative-works",
    campus: "riverside",
    title: "Reclaiming the context of creative works",
    summary:
      "New research led by a UC Riverside professor has developed an AI tool that compensates for the shifting genre perceptions that impact how creative works are understood, evaluated, and even discovered. ",
    publishedAt: "",
    sourceUrl: "https://news.ucr.edu/articles/2026/04/22/reclaiming-context-creative-works",
    imageUrl:
      "https://news.ucr.edu/sites/default/files/2026-04/960-gettyimages-2264305709-copy.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-ucr-report-urges-broadband-be-state-utility",
    campus: "riverside",
    title: "UCR report urges broadband to be a state utility",
    summary:
      "California should regulate broadband internet providers like public utilities — imposing rate controls, universal access requirements, and reliability standards to ensure every resident has affordable, high-speed internet access, according to a new UC Riverside public policy report.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2026/02/12/ucr-report-urges-broadband-be-state-utility",
    imageUrl: "https://news.ucr.edu/sites/default/files/2026-02/960-gettyimages-2231090399.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-tangos-sweet-legacy-lives",
    campus: "riverside",
    title: "Tango’s sweet legacy lives on",
    summary:
      "The UCR-developed Tango mandarin has established itself as a symbol of innovation and sustainability in the global citrus market, generating more than $70 million in cumulative economic value for the university.",
    publishedAt: "",
    sourceUrl: "https://news.ucr.edu/articles/2026/01/15/tangos-sweet-legacy-lives",
    imageUrl: "https://news.ucr.edu/sites/default/files/2026-01/960-2025-11-05_tango_004.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-slower-company-acquisition-pace-can-boost-corporate-values",
    campus: "riverside",
    title: "Slower company acquisition pace can boost corporate values",
    summary:
      "Expanding the time between company acquisitions improves the integration of the new assets and increases corporate values, study finds.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/12/08/slower-company-acquisition-pace-can-boost-corporate-values",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-12/960-gettyimages-147205360.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-shopping-two-stressful",
    campus: "riverside",
    title: "Shopping for two is stressful",
    summary:
      "A study co-authored by a UCR business professor finds that shopping for goods or services that you will share is significantly more stressful than shopping for yourself or for something to be given to another person.",
    publishedAt: "",
    sourceUrl: "https://news.ucr.edu/articles/2025/12/02/shopping-two-stressful",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-12/960-stressed-shopper.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-study-finds-lower-emissions-higher-ethanol-gasoline",
    campus: "riverside",
    title: "Study finds lower emissions from higher-ethanol gasoline",
    summary:
      "Landmark UC Riverside vehicle emissions study allows California to move forward with less costly and less polluting gasoline blend.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/11/25/study-finds-lower-emissions-higher-ethanol-gasoline",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-11/960-gettyimages-188115695-1_0.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-mccollum-familys-march-toward-graduation-stage",
    campus: "riverside",
    title: "The McCollum family’s march toward the graduation stage",
    summary: "",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/11/09/mccollum-familys-march-toward-graduation-stage",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-11/veteran_business_mccollum_2025.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-study-finds-moral-costs-over-pricing-essentials",
    campus: "riverside",
    title: "Study finds moral costs in over-pricing for essentials",
    summary:
      "A study led by UC Riverside School of Business professor Margaret C. Campbell found that when companies hike prices on essentials like food, medicine, or medical devices, the financial rewards may be immediate—but the reputational damage may linger and ultimately cost more in the long run.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/11/03/study-finds-moral-costs-over-pricing-essentials",
    imageUrl:
      "https://news.ucr.edu/sites/default/files/2025-11/960-ex-gettyimages-1793165463-copy.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-private-equity-takes-airports-new-heights",
    campus: "riverside",
    title: "Private equity takes airports to new heights",
    summary:
      "Equity investors improved airport operating and customer service, finds a global study that spanned two decades and four continents.",
    publishedAt: "",
    sourceUrl: "https://news.ucr.edu/articles/2025/10/13/private-equity-takes-airports-new-heights",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-10/madrid-airport.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-farm-conservation-economical-path-save-river-water",
    campus: "riverside",
    title: "Farm conservation is an economical path to save river water",
    summary:
      "The most cost-effective way to conserve the dwindling waters of the Colorado River may not come from building new reservoirs, canals, or wells, but from changing how water is used on farms that consume most of it.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/09/29/farm-conservation-economical-path-save-river-water",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-09/960-gettyimages-90285343.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-ucr-computer-scientists-boost-us-cybersecurity",
    campus: "riverside",
    title: "UCR computer scientists boost US cybersecurity",
    summary:
      "UCR computer scientists are developing tools to expose hidden cybersecurity vulnerabilities, protect private data, and strengthen the digital defenses that safeguard everything from personal communications to national infrastructure.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/09/18/ucr-computer-scientists-boost-us-cybersecurity",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-09/960-gettyimages-2174551157.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-report-inland-empire-warehouse-workers-make-gains-through-collective-action",
    campus: "riverside",
    title: "Report: Inland Empire warehouse workers make gains through collective action",
    summary:
      "In “State of the Unions: California Labor in 2024,” UCR researchers offer details on the growth, salaries, ethnicities, and ongoing struggles of warehouse workers in Riverside and San Bernardino counties",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/09/08/report-inland-empire-warehouse-workers-make-gains-through-collective-action",
    imageUrl: "https://news.ucr.edu/sites/default/files/2018-09/warehouse.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-nostalgia-asset-company-acquisitions",
    campus: "riverside",
    title: "Nostalgia is an asset in company acquisitions",
    summary:
      "A study by UCR School of Business scholars found that nostalgia serves as a comforting and stabilizing force during company acquisition periods when employees feel vulnerable, fear losing their jobs, status, or advancement opportunities, and are thus inclined to send out résumés.",
    publishedAt: "",
    sourceUrl: "https://news.ucr.edu/articles/2025/08/20/nostalgia-asset-company-acquisitions",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-10/gettyimages-2238047024.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-groundwater-depletion-sinks-home-prices-californias-central-valley",
    campus: "riverside",
    title: "Groundwater depletion sinks home prices in California's Central Valley",
    summary:
      "UC Riverside study has found that subsidence from excessive groundwater pumping in California's Central Valley reduced home values between 2.4% and 5.8% or between $6,689 and $16,165 per home. These costs totaled $1.87 billion in aggregate housing value lost, the study estimated.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/07/31/groundwater-depletion-sinks-home-prices-californias-central-valley",
    imageUrl:
      "https://news.ucr.edu/sites/default/files/2025-07/960-gettyimages-2208627482-copy.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-school-business-joins-council-global-business-schools",
    campus: "riverside",
    title: "School of Business joins council of global business schools",
    summary:
      "UC Riverside’s School of Business has been accepted into the Graduate Management Admission Council, or GMAC, a prestigious global association of leading graduate business schools.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/07/17/school-business-joins-council-global-business-schools",
    imageUrl:
      "https://news.ucr.edu/sites/default/files/2025-07/960-2024-10-18_business_ribbon_cutting_139-copy_0_0.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-uc-riverside-scholar-reimagines-student-engagement",
    campus: "riverside",
    title: "UC Riverside scholar reimagines student engagement",
    summary:
      'The "Carry the Class" teaching method helps college students master concepts while fostering a sense of ownership through more meaningful social interactions among students and faculty, which creates a sense of community and shared purpose.',
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/07/07/uc-riverside-scholar-reimagines-student-engagement",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-07/960-header-kyle-ingram.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-state-workers-report-addresses-ev-transition",
    campus: "riverside",
    title: "State of Workers report addresses EV transition",
    summary:
      "Today at the State of Workers in the Inland Empire report release,  UC Riverside investigators presented recent statistics on labor market demographics, wages, cost of living, and worker training needs to adapt to changing conditions and emerging technologies such as electric vehicles, or EVs.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/06/10/state-workers-report-addresses-ev-transition",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-06/gettyimages-1406501364_1.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-ucr-launches-study-ship-emissions-socal-coast",
    campus: "riverside",
    title: "UCR launches study of ship emissions off SoCal coast",
    summary:
      "A team of UC Riverside environmental engineers are embarking on a $3.5 million study of air pollution from massive oceangoing vessels that frequent the ports of Los Angeles and Long Beach—one of the region’s largest sources of toxic air pollution.",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/06/02/ucr-launches-study-ship-emissions-socal-coast",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-06/960-gettyimages-1297687827.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-it-good-know-how-much-your-co-workers-make",
    campus: "riverside",
    title: "Is it good to know how much your co-workers make?",
    summary:
      "Many companies keep employee pay shrouded in secrecy while other employers make such information known to their workers. So, what are the impacts of compensation transparency? ",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/04/07/it-good-know-how-much-your-co-workers-make",
    imageUrl:
      "https://news.ucr.edu/sites/default/files/2025-04/960-gettyimages-1258125025-copy-2_1.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "riverside-democracies-boost-womens-participation-labor-market",
    campus: "riverside",
    title: "Democracies boost women’s participation in the labor market",
    summary: "UCR study finds freer, democratic societies compel more women to pursue careers",
    publishedAt: "",
    sourceUrl:
      "https://news.ucr.edu/articles/2025/03/13/democracies-boost-womens-participation-labor-market",
    imageUrl: "https://news.ucr.edu/sites/default/files/2025-03/960-gettyimages-3308588.jpg",
    sourceHost: "news.ucr.edu",
  },
  {
    id: "sf-scientists-create-cancer-fighting-immune-cells-right-body",
    campus: "sf",
    title: "Scientists Create Cancer-Fighting Immune Cells Right in the Body",
    summary: "Scientists Create Cancer-Fighting Immune Cells Right in the Body",
    publishedAt: "",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/scientists-create-cancer-fighting-immune-cells-right-body",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-molecular-garbage-tumors-makes-easy-target-antibody-drugs",
    campus: "sf",
    title: "Molecular Garbage on Tumors Makes Easy Target for Antibody Drugs",
    summary:
      "Cancer cells can ‘barf’ proteins onto their cell surface. That may create new targets for immunotherapies",
    publishedAt: "",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/molecular-garbage-tumors-makes-easy-target-antibody-drugs",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-ge-healthcare-ucsf-health-form-10-year-imaging-collaboration",
    campus: "sf",
    title: "GE HealthCare, UCSF Health form 10-year imaging collaboration",
    summary:
      "GE HealthCare has entered a 10-year Care Alliance with UCSF Health aimed at expanding imaging capabilities and supporting clinical operations across the health system.",
    publishedAt: "",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/ge-healthcare-ucsf-health-form-10-year-imaging-collaboration",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-tissue-repair-slows-old-age-these-proteins-speed-it-back",
    campus: "sf",
    title: "Tissue Repair Slows in Old Age. These Proteins Speed It Back Up",
    summary: "Tissue Repair Slows in Old Age. These Proteins Speed It Back Up",
    publishedAt: "",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/tissue-repair-slows-old-age-these-proteins-speed-it-back",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-tahoe-therapeutics-arc-institute-and-biohub-partner-generate-largest-perturbation",
    campus: "sf",
    title:
      "Tahoe Therapeutics, Arc Institute, and Biohub Partner to Generate the Largest Perturbation Dataset for Virtual Cell Models",
    summary:
      "Tahoe Therapeutics, Arc Institute, and Biohub Partner to Generate the Largest Perturbation Dataset for Virtual Cell Models",
    publishedAt: "",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/tahoe-therapeutics-arc-institute-and-biohub-partner-generate-largest-perturbation",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-jj-google-venture-arms",
    campus: "sf",
    title:
      "J&J, Google venture arms line up to back protein degradation biotech EpiBiologics' $107M series B",
    summary:
      "Protein degradation biotech EpiBiologics has brought in $107 million in a&nbsp;star-studded series B round&nbsp;headed up by Johnson &amp; Johnson's and Google's respective venture arms.",
    publishedAt: "",
    sourceUrl: "https://innovation.ucsf.edu/media/news/jj-google-venture-arms",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
  {
    id: "sf-trial-library-raises-10m-sell-clinical-trial-matching-insurers",
    campus: "sf",
    title: "Trial Library raises $10M to sell clinical trial matching to insurers",
    summary: "Trial Library raises $10M to sell clinical trial matching to insurers",
    publishedAt: "",
    sourceUrl:
      "https://innovation.ucsf.edu/media/news/trial-library-raises-10m-sell-clinical-trial-matching-insurers",
    imageUrl:
      "sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    sourceHost: "innovation.ucsf.edu",
  },
];
