// AUTO-GENERATED by `vp run build-news-data`. Do not edit by hand.
// Source: data/news/*.json — last refresh: 2026-09-06T13:16:35.205Z
// Run `vp run crawl:news` followed by `vp run build-news-data` to refresh.
import type { NewsItem } from "./news.ts";

export const NEWS: NewsItem[] = [
  {
    "id": "berkeley-citris-uc-org-citris-berkeley-discovery-partner-with-tech-europe-foundation",
    "campus": "berkeley",
    "title": "CITRIS, Berkeley Discovery partner with Tech Europe Foundation",
    "summary": "CITRIS, Berkeley Discovery partner with Tech Europe Foundation",
    "publishedAt": "2026-09-02T17:07:00.000Z",
    "sourceUrl": "https://citris-uc.org/citris-berkeley-discovery-partner-with-tech-europe-foundation/?utm_source=rss&utm_medium=rss&utm_campaign=citris-berkeley-discovery-partner-with-tech-europe-foundation",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/09/TEF-Banner-1540x368-1-768x184.jpg",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "santacruz-news-ucsc-edu-five-uc-santa-cruz-innovators-nominated-for-inaugural-uc-regents-innovation-awards",
    "campus": "santacruz",
    "title": "Five UC Santa Cruz innovators nominated for inaugural UC Regents Innovation Awards",
    "summary": "The campus’s nominees span innovations in climate adaptation, disease treatment, health and community development.",
    "publishedAt": "2026-09-01T22:17:28.000Z",
    "sourceUrl": "https://news.ucsc.edu/2026/09/five-uc-santa-cruz-innovators-nominated-for-inaugural-uc-regents-innovation-awards/",
    "imageUrl": "https://news.ucsc.edu/wp-content/uploads/2026/09/uc-innovation-e1788300945246.jpg",
    "sourceHost": "news.ucsc.edu"
  },
  {
    "id": "berkeley-qb3-berkeley-edu-robert-thorne-pir",
    "campus": "berkeley",
    "title": "From butterfly chasing to team science: Professional in Residence Robert Thorne on science in biotech",
    "summary": "Robert Thorne, PhD, has spent more than three decades studying one of the central challenges in neuroscience: how to deliver therapeutics to the brain. After years in academia, including eight…",
    "publishedAt": "2026-09-01T17:59:00.000Z",
    "sourceUrl": "https://qb3.berkeley.edu/news/science-writing-for-the-public/robert-thorne-pir/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/09/robert_g._thorne-208x300.jpg",
    "sourceHost": "qb3.berkeley.edu"
  },
  {
    "id": "berkeley-citris-uc-org-citris-cdss-and-aic-invite-proposals-for-faculty-innovation-fellowships-2",
    "campus": "berkeley",
    "title": "CITRIS, CDSS and AIC invite proposals for faculty innovation fellowships",
    "summary": "CITRIS, CDSS and AIC invite proposals for faculty innovation fellowships",
    "publishedAt": "2026-09-01T16:00:00.000Z",
    "sourceUrl": "https://citris-uc.org/citris-cdss-and-aic-invite-proposals-for-faculty-innovation-fellowships-2/?utm_source=rss&utm_medium=rss&utm_campaign=citris-cdss-and-aic-invite-proposals-for-faculty-innovation-fellowships-2",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/09/AIC-Web-Banner-2026-768x184.jpg",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "berkeley-haas-berkeley-edu-from-berkeley-to-paris-toppan-superapps-and-a-truly-heroic-amount-of-bread",
    "campus": "berkeley",
    "title": "From Berkeley to Paris: TOPPAN, superapps, and a truly heroic amount of bread",
    "summary": "The post From Berkeley to Paris: TOPPAN, superapps, and a truly heroic amount of bread appeared first on Haas News | UC Berkeley Haas. Source link",
    "publishedAt": "2026-08-31T18:11:00.000Z",
    "sourceUrl": "https://haas.berkeley.edu/international-business-development/blog/posts/from-berkeley-to-paris-toppan-superapps-and-a-truly-heroic-amount-of-bread/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/09/Toppan_France_1.png",
    "sourceHost": "haas.berkeley.edu"
  },
  {
    "id": "berkeley-energyathaas-wordpress-com-did-the-china-shock-increase-air-conditioning-adoption",
    "campus": "berkeley",
    "title": "Did the China shock increase air conditioning adoption?",
    "summary": "The post Did the China shock increase air conditioning adoption? appeared first on Haas News | UC Berkeley Haas. Source link",
    "publishedAt": "2026-08-31T18:06:00.000Z",
    "sourceUrl": "https://energyathaas.wordpress.com/2026/08/31/did-the-china-shock-increase-air-conditioning-adoption/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/09/Photo-of-a-large-brick-building-showing-windows-with-AC-units-in-them.png",
    "sourceHost": "energyathaas.wordpress.com"
  },
  {
    "id": "sd-today-ucsd-edu-wildfire-losses-have-lasting-economic-consequences-for-homeowners",
    "campus": "sd",
    "title": "Wildfire Losses Have Lasting Economic Consequences for Homeowners",
    "summary": "A new National Bureau of Economic Research from the University of California San Diego shows that wildfire damage can have long-term economic consequences for households, resulting in income losses, relocation of residents as well as slow rebuilding for several years after a fire.",
    "publishedAt": "2026-08-31T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/wildfire-losses-have-lasting-economic-consequences-for-homeowners",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/iStock-1008290204%282%29%281%29.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-glytr",
    "campus": "irvine",
    "title": "GlyTR",
    "summary": "The Sweet Spot in Cancer Immunotherapy",
    "publishedAt": "2026-08-28T19:26:33.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/glytr/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/08/GlyTR-wide-scaled.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "berkeley-citris-uc-org-citris-researchers-monitor-yuba-county-flood-barriers",
    "campus": "berkeley",
    "title": "CITRIS researchers monitor Yuba County’s flood barriers",
    "summary": "CITRIS researchers monitor Yuba County’s flood barriers",
    "publishedAt": "2026-08-27T16:00:00.000Z",
    "sourceUrl": "https://citris-uc.org/citris-researchers-monitor-yuba-county-flood-barriers/?utm_source=rss&utm_medium=rss&utm_campaign=citris-researchers-monitor-yuba-county-flood-barriers",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/08/Yuba-County-Aug-2026-768x184.png",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "berkeley-citris-uc-org-were-hiring-program-manager-for-tech-policy-workforce-development",
    "campus": "berkeley",
    "title": "We’re hiring: Program Manager for Tech Policy & Workforce Development",
    "summary": "We’re hiring: Program Manager for Tech Policy & Workforce Development",
    "publishedAt": "2026-08-25T17:00:00.000Z",
    "sourceUrl": "https://citris-uc.org/were-hiring-program-manager-for-tech-policy-workforce-development/?utm_source=rss&utm_medium=rss&utm_campaign=were-hiring-program-manager-for-tech-policy-workforce-development",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/08/banner-tech-policy-week-sacramento-capitol-credit-canva-pro-1540x368ox-768x184.jpg",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "sf-innovation-ucsf-edu-stumped-medical-mystery-try-metagenomics",
    "campus": "sf",
    "title": "Stumped by a Medical Mystery? Try Metagenomics",
    "summary": "Stumped by a Medical Mystery? Try Metagenomics. When doctors can’t figure out what’s ailing us, they can search our bodies for snippets of genetic material from viruses, bacteria, and fungi.",
    "publishedAt": "2026-08-25T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/stumped-medical-mystery-try-metagenomics",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "berkeley-energyathaas-wordpress-com-who-should-pay-for-utility-ignited-wildfires",
    "campus": "berkeley",
    "title": "Who should pay for utility-ignited wildfires?",
    "summary": "The post Who should pay for utility-ignited wildfires? appeared first on Haas News | UC Berkeley Haas. Source link",
    "publishedAt": "2026-08-24T18:38:00.000Z",
    "sourceUrl": "https://energyathaas.wordpress.com/2026/08/24/who-should-pay-for-utility-ignited-wildfires/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/08/Photo-of-fire-and-smoke.-Image-also-features-a-tree-and-car-768x520.png",
    "sourceHost": "energyathaas.wordpress.com"
  },
  {
    "id": "berkeley-cmr-berkeley-edu-when-ai-thinks-with-you-governing-the-strategic-reasoning-of-the-firm",
    "campus": "berkeley",
    "title": "When AI thinks with you: Governing the strategic reasoning of the firm",
    "summary": "The post When AI thinks with you: Governing the strategic reasoning of the firm appeared first on Haas News | UC Berkeley Haas. Source link",
    "publishedAt": "2026-08-24T18:20:00.000Z",
    "sourceUrl": "https://cmr.berkeley.edu/2026/08/when-ai-thinks-with-you-governing-the-strategic-reasoning-of-the-firm/",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/09/2026-08-li_as_498529467-768x512.jpeg",
    "sourceHost": "cmr.berkeley.edu"
  },
  {
    "id": "berkeley-citris-uc-org-california-legislature-honors-dado-banatao",
    "campus": "berkeley",
    "title": "California Legislature honors Dado Banatao",
    "summary": "California Legislature honors Dado Banatao",
    "publishedAt": "2026-08-24T16:00:00.000Z",
    "sourceUrl": "https://citris-uc.org/california-legislature-honors-dado-banatao/?utm_source=rss&utm_medium=rss&utm_campaign=california-legislature-honors-dado-banatao",
    "imageUrl": "https://begin.berkeley.edu/wp-content/uploads/2026/08/Dado-Banatao-Honored-Aug-2026-768x184.png",
    "sourceHost": "citris-uc.org"
  },
  {
    "id": "sf-innovation-ucsf-edu-jocasta-signs-ucsf-licensing-agreement-advance-klotho-managing-cognitive-impairment",
    "campus": "sf",
    "title": "Jocasta Signs UCSF Licensing Agreement to Advance α-klotho for Managing Cognitive Impairment",
    "summary": "Jocasta Signs UCSF Licensing Agreement to Advance α-klotho for Managing Cognitive Impairment",
    "publishedAt": "2026-08-20T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/jocasta-signs-ucsf-licensing-agreement-advance-klotho-managing-cognitive-impairment",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sd-today-ucsd-edu-are-tariffs-making-prices-go-up",
    "campus": "sd",
    "title": "Are Tariffs Making Prices Go Up?",
    "summary": "As Americans continue to worry about the cost of living, U.S. tariffs are back in the news. So we asked international trade economist and School of Global Policy and Strategy Dean Caroline Freund the question on many consumers' minds.",
    "publishedAt": "2026-08-17T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/are-tariffs-making-prices-go-up",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Shopping-Receipt-photo-by-iStock_M_Stock-1468272596.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-nexus-photonics-acquired-ionq",
    "campus": "santabarbara",
    "title": "Nexus Photonics Acquired by IonQ",
    "summary": "Nexus Photonics Acquired by IonQ margalith Thu, 08/13/2026 - 07:59 UCSB spinoff Nexus Photonics has been acquired by IonQ. In their second quarter update, IonQ notes the acquisition as a highlight: \"The successful close of our SkyWater and Nexus acquisitions extends IonQ’s full-stack quantum platform and merchant supplier leadership to the U.S. and allied ecosystem\". Blog News Topics UCSB Startups",
    "publishedAt": "2026-08-13T14:59:01.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/nexus-photonics-acquired-ionq",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "merced-news-ucmerced-edu-chancellors-catalyst-awards-ignite-research-humanities-social-sciences",
    "campus": "merced",
    "title": "Chancellor's Catalyst Awards Ignite Research in Humanities, Social Sciences",
    "summary": "By Jody Murray, UC Merced August 12, 2026 The site of Mariposa County Gold Rush town Agua Fria will be the subject of an archeological study by UC Merced faculty and students. Digging for stories in a Gold Rush town that vanished in flames 170 years ago. Pinging brainwaves for reactions from sentences that slide between Spanish and English. Fortifying students’ skills and confidence with a practic",
    "publishedAt": "2026-08-12T14:55:44.000Z",
    "sourceUrl": "https://news.ucmerced.edu/news/2026/chancellors-catalyst-awards-ignite-research-humanities-social-sciences",
    "imageUrl": "https://news.ucmerced.edu/sites/g/files/ufvvjh1306/f/news/image/uc-merced-agua-fria-gold-rush-town-site-marker.jpg",
    "sourceHost": "news.ucmerced.edu"
  },
  {
    "id": "sd-today-ucsd-edu-why-a-doctor-saying-its-normal-can-backfire",
    "campus": "sd",
    "title": "Why a Doctor Saying ‘It’s Normal’ Can Backfire",
    "summary": "Research shows that patients often interpret normalizing language to mean treatment isn’t necessary, but the misunderstanding can be prevented.",
    "publishedAt": "2026-08-10T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/why-a-doctor-saying-its-normal-can-backfire",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Patient-describing-symptoms-photo-by-iStock_Matinee_Duangphet-2232809248.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-chugai-and-ucsf-establish-master-collaboration-agreement-drug-discovery-research",
    "campus": "sf",
    "title": "Chugai and UCSF Establish Master Collaboration Agreement for Drug Discovery Research",
    "summary": "Chugai and UCSF Establish Master Collaboration Agreement for Drug Discovery Research. A Framework to Streamline Future Research Projects",
    "publishedAt": "2026-08-06T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/chugai-and-ucsf-establish-master-collaboration-agreement-drug-discovery-research",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sd-today-ucsd-edu-mindfulness-based-therapy-for-opioid-misuse-offers-massive-return-on-investment",
    "campus": "sd",
    "title": "Mindfulness-Based Therapy for Opioid Misuse Offers Massive Return on Investment",
    "summary": "A mindfulness-based treatment for opioid use disorder could generate $12 in economic benefit for every dollar spent, a massive improvement on current approaches.",
    "publishedAt": "2026-08-05T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/mindfulness-based-therapy-for-opioid-misuse-offers-massive-return-on-investment",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Garland-Screenshot-1200x628.png",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "sd-today-ucsd-edu-uc-san-diego-launches-new-business-data-science-major",
    "campus": "sd",
    "title": "UC San Diego Launches New Business Data Science Major",
    "summary": "The first program of its kind in the UC system, a new bachelor’s degree from the Halıcıoğlu School for Data Science and Computing and the Rady School of Management will enable students to turn data into strategic business decisions.",
    "publishedAt": "2026-08-03T07:00:00.000Z",
    "sourceUrl": "https://today.ucsd.edu/story/uc-san-diego-launches-new-business-data-science-major",
    "imageUrl": "https://today.ucsd.edu/teaser_uploads/_social/Business-Data-photo-by-iStock_Artem_Peretiatko-1276832767.jpg",
    "sourceHost": "today.ucsd.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-ucsb-partnership-opens-doors-semiconductor-careers-high-school-students",
    "campus": "santabarbara",
    "title": "UCSB Partnership Opens Doors to Semiconductor Careers for High School Students",
    "summary": "UCSB Partnership Opens Doors to Semiconductor Careers for High School Students gmundaden Tue, 07/28/2026 - 12:31 A new partnership between UC Santa Barbara’s Nanofabrication Facility and semiconductor startup PseudolithIC is giving Carpinteria High School (CHS) students a rare hands-on experience in semiconductor engineering while helping to build a future workforce for one of Santa Barbara County",
    "publishedAt": "2026-07-28T19:31:32.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/ucsb-partnership-opens-doors-semiconductor-careers-high-school-students",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-07/classroom-to-cleanroom.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-hurd-co-named-finalists-2026-thrive-global-impact-challenge",
    "campus": "santabarbara",
    "title": "The Hurd Co. named finalists in the 2026 THRIVE Global Impact Challenge",
    "summary": "The Hurd Co. named finalists in the 2026 THRIVE Global Impact Challenge margalith Mon, 07/27/2026 - 12:44 The Hurd Co. has been named one of 18 finalists (out of more than 2,000 global applicants) in the 2026 THRIVE Global Impact Challenge by SVG Ventures! Finalists compete for up to $1M in investment while pitching on stage in Silicon Valley at the THRIVE Global Impact Summit in October 2026. Rep",
    "publishedAt": "2026-07-27T19:44:57.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/hurd-co-named-finalists-2026-thrive-global-impact-challenge",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-07/Hurd_Co_Logo.png.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-jonathan-klamkin-receives-international-semiconductor-award",
    "campus": "santabarbara",
    "title": "Jonathan Klamkin Receives International Semiconductor Award",
    "summary": "Jonathan Klamkin Receives International Semiconductor Award gmundaden Wed, 07/15/2026 - 15:35 Compound Semiconductor Week is widely regarded as one of the premier international gatherings in the field, bringing together researchers and industry leaders who work on the science, technology, and applications of compound semiconductors. Jonathan Klamkin and other recipients were recognized during an a",
    "publishedAt": "2026-07-15T22:35:07.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/jonathan-klamkin-receives-international-semiconductor-award",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-07/klamkin-csw-iprm-caption.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-ucsb-professor-earns-international-recognition-materials-research",
    "campus": "santabarbara",
    "title": "UCSB Professor Earns International Recognition for Materials Research",
    "summary": "UCSB Professor Earns International Recognition for Materials Research gmundaden Wed, 07/15/2026 - 15:27 Some people seek perfection. UC Santa Barbara materials professor Daniel Gianola is focused on creating, finding and exploring imperfections, with an eye to developing new and better materials. “Our work is all about the imperfections — defects — because they control a material’s properties, so",
    "publishedAt": "2026-07-15T22:27:23.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/ucsb-professor-earns-international-recognition-materials-research",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-07/gianola.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-aggie-venture-accelerator-welcomes-inaugural-cohort-life-science-startups",
    "campus": "davis",
    "title": "Aggie Venture Accelerator Welcomes Inaugural Cohort of Life Science Startups",
    "summary": "UC Davis launches Aggie Venture Accelerator, welcoming inaugural cohort of life science startups—SinewUS, Pharm to Food and ThriveSpan Labs—offering mentorship, industry connections and funding to fast-track commercialization.",
    "publishedAt": "2026-07-13T22:31:28.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/aggie-venture-accelerator-welcomes-inaugural-cohort-life-science-startups",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_6025_0.jpg?h=4997dc06&itok=b5QpEIh2",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-united-therapeutics-corporation-acquires-thymmune-therapeutics",
    "campus": "sf",
    "title": "United Therapeutics Corporation Acquires Thymmune Therapeutics",
    "summary": "United Therapeutics Corporation Acquires Thymmune Therapeutics",
    "publishedAt": "2026-07-06T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/united-therapeutics-corporation-acquires-thymmune-therapeutics",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-ucsf-innovation-translates-discovery-life-saving-diagnostics",
    "campus": "sf",
    "title": "UCSF Innovation Translates Discovery into Life-Saving Diagnostics",
    "summary": "UCSF Innovation Translates Discovery into Life-Saving Diagnostics",
    "publishedAt": "2026-06-26T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ucsf-innovation-translates-discovery-life-saving-diagnostics",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-mentium-technologies-luna-r1-ai-chip-selected-et-01-constellation-mission-first-multi",
    "campus": "santabarbara",
    "title": "Mentium Technologies’ Luna-R1 AI Chip Selected for ET-01 Constellation Mission, First Multi-Satellite Deployment of Mentium Hardware",
    "summary": "Mentium Technologies’ Luna-R1 AI Chip Selected for ET-01 Constellation Mission, First Multi-Satellite Deployment of Mentium Hardware abeal Tue, 06/23/2026 - 09:49 Launching on SpaceX Transporter-17 to Enable Autonomous Intelligence Across LEO Satellite Networks Mentium Technologies today announced that its next-generation AI processing chip, Luna-R1 , has been selected for deployment on the ET-01",
    "publishedAt": "2026-06-23T16:49:12.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/mentium-technologies-luna-r1-ai-chip-selected-et-01-constellation-mission-first-multi",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-06/mentium.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-aquatex",
    "campus": "irvine",
    "title": "The Problem with Good Enough",
    "summary": "UC Irvine startup Cytoseen detects new drug targets for cancer and neurodegeneration.",
    "publishedAt": "2026-06-15T16:04:44.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/aquatex/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/06/AquaTex-1.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-aelumas-ceo-jonathan-klamkin-receive-iprm-award",
    "campus": "santabarbara",
    "title": "Aeluma’s CEO Jonathan Klamkin to Receive IPRM Award",
    "summary": "Aeluma’s CEO Jonathan Klamkin to Receive IPRM Award gmundaden Mon, 06/01/2026 - 10:15 Aeluma, Inc. (NASDAQ: ALMU), a semiconductor company specializing in high-performance, scalable technologies for mobile, AI, defense and aerospace, robotics, automotive, AR/VR, and quantum, announced today that President and CEO Jonathan Klamkin, Ph.D. will receive the prestigious Indium Phosphide and Related Mat",
    "publishedAt": "2026-06-01T17:15:10.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/aelumas-ceo-jonathan-klamkin-receive-iprm-award",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-06/images.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-stair-health-program-invests-faculty-led-health-innovations",
    "campus": "davis",
    "title": "UC Davis STAIR HEALTH Program Invests in Faculty-led Health Innovations",
    "summary": "UC Davis Health awarded more than $390,000 through its STAIR HEALTH proof-of-concept program to support three interdisciplinary research teams advancing promising innovations in cancer imaging, spinal cord injury treatment and breast cancer therapeutics toward commercial and clinical impact.",
    "publishedAt": "2026-05-21T15:35:24.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-stair-health-program-invests-faculty-led-health-innovations",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/2025-07-01_48X29.jpg?h=36f8b718&itok=NM0BJTFI",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-how-impossible-idea-led-pancreatic-cancer-breakthrough",
    "campus": "sf",
    "title": "How an ‘Impossible’ Idea Led to a Pancreatic Cancer Breakthrough",
    "summary": "How an ‘Impossible’ Idea Led to a Pancreatic Cancer Breakthrough",
    "publishedAt": "2026-05-12T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/how-impossible-idea-led-pancreatic-cancer-breakthrough",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-born-amplifye-targets-new-frontier-protein-efficiency-amid-glp-1-era",
    "campus": "davis",
    "title": "UC Davis–born amplifye Targets a New Frontier in Protein Efficiency Amid GLP-1 Era",
    "summary": "Born out of cross-disciplinary research at University of California, Davis, startup amplifye is developing enzyme-based technology designed to improve protein absorption and muscle health as growing use of GLP-1 therapies reshapes nutrition and metabolic health needs.",
    "publishedAt": "2026-05-11T15:30:03.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-born-amplifye-targets-new-frontier-protein-efficiency-amid-glp-1-era",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/amplifye%20article%20image_1280x720.jpg?h=3e07f1d9&itok=rPIUdxsO",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-cytoseen",
    "campus": "irvine",
    "title": "Seeing the Unseen in Disease",
    "summary": "UC Irvine startup Cytoseen detects new drug targets for cancer and neurodegeneration.",
    "publishedAt": "2026-05-08T22:46:18.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/cytoseen/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/05/Cytoseen-scaled.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-beacon-photonics-first-industry-member-ucsb-oasis",
    "campus": "santabarbara",
    "title": "Beacon Photonics First Industry Member at UCSB OASIS",
    "summary": "Beacon Photonics First Industry Member at UCSB OASIS gmundaden Mon, 05/04/2026 - 10:15 Beacon Photonics has become the first industry member of OASIS, UC Santa Barbara’s new innovation and translational research hub, marking an early milestone for the 105,000-square-foot facility designed to bring together established companies, startups, and academic researchers. Managed by The Robert Mehrabian C",
    "publishedAt": "2026-05-04T17:15:57.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/beacon-photonics-first-industry-member-ucsb-oasis",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-05/BEACON_OASIS.jpg",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "santabarbara-innovation-ucsb-edu-new-venture-competition-finalists-2026",
    "campus": "santabarbara",
    "title": "New Venture Competition Finalists 2026",
    "summary": "New Venture Competition Finalists 2026 gmundaden Wed, 04/29/2026 - 11:41 Congrats to the New Venture Competition Finalists of 2026! Register for the New Venture Finals, Wednesday, May 20, 2026 at 3:30 PM PST in Corwin Pavilion. MediMRF is a modular, AI-enabled waste-sorting system for hospitals, automating the identification and removal of hazardous materials from waste streams. mimic is building",
    "publishedAt": "2026-04-29T18:41:35.000Z",
    "sourceUrl": "https://innovation.ucsb.edu/blog/news/new-venture-competition-finalists-2026",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2026-04/Untitled%20design_0.png",
    "sourceHost": "innovation.ucsb.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-born-in-california-2026",
    "campus": "irvine",
    "title": "The Pipeline",
    "summary": "What does it take to make a UC idea matter in the real world?",
    "publishedAt": "2026-04-29T16:30:40.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/born-in-california-2026/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2023/01/Neried-biomaterials1.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-qa-nicholas-hertz-president-ceo-montara-therapeutics",
    "campus": "sf",
    "title": "Q&A with Nicholas Hertz, President & CEO of Montara Therapeutics",
    "summary": "Q&A with Nicholas Hertz, President & CEO of Montara Therapeutics",
    "publishedAt": "2026-04-29T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/qa-nicholas-hertz-president-ceo-montara-therapeutics",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-breakthrough-device-designation-aidabreastr-early-stage-invasive-breast-cancer-assay",
    "campus": "sf",
    "title": "Breakthrough Device Designation for AidaBREAST® - Early-Stage Invasive Breast Cancer Assay",
    "summary": "Breakthrough Device Designation for AidaBREAST® - Early-Stage Invasive Breast Cancer Assay",
    "publishedAt": "2026-04-29T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/breakthrough-device-designation-aidabreastr-early-stage-invasive-breast-cancer-assay",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-ecotune",
    "campus": "irvine",
    "title": "The Material Question",
    "summary": "What if materials weren’t just made, but designed in tune with nature?",
    "publishedAt": "2026-04-24T22:38:57.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/ecotune/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/04/Ecotune-scaled.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-ucb-acquire-neurona-therapeutics-advancing-its-innovative-leadership-epilepsy-through",
    "campus": "sf",
    "title": "UCB to acquire Neurona Therapeutics, advancing its innovative leadership in epilepsy through regenerative science",
    "summary": "UCB to acquire Neurona Therapeutics, advancing its innovative leadership in epilepsy through regenerative science",
    "publishedAt": "2026-04-17T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ucb-acquire-neurona-therapeutics-advancing-its-innovative-leadership-epilepsy-through",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-sounddose",
    "campus": "irvine",
    "title": "The Blind Spot in Modern Radiation Therapy",
    "summary": "How UC Irvine startup SoundDose is tackling one of cancer care’s biggest unknowns",
    "publishedAt": "2026-04-15T19:13:47.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/sounddose/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/04/Sound-Dose.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "la-anderson-ucla-edu-ucla-anderson-school-management-launches-minors-real-estate-and-sports-leadership-and-management",
    "campus": "la",
    "title": "UCLA Anderson School of Management Launches Minors in Real Estate and Sports Leadership and Management",
    "summary": "The two new minors expand the school’s undergraduate offerings, which include minors in Accounting and Entrepreneurship",
    "publishedAt": "2026-04-15T19:00:00.000Z",
    "sourceUrl": "https://www.anderson.ucla.edu/news-and-events/ucla-anderson-school-management-launches-minors-real-estate-and-sports-leadership-and-management",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/social_og/public/image/2026-04/20260415-campus-drone-card.jpg.jpeg?itok=QzAacVws",
    "sourceHost": "www.anderson.ucla.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-launches-aggie-venture-accelerator-advance-early-stage-life-science-innovation",
    "campus": "davis",
    "title": "UC Davis Launches Aggie Venture Accelerator to Advance Early Stage Life Science Innovation",
    "summary": "The UC Davis Innovation and Economic Development Office has launched the Aggie Venture Accelerator, an initiative designed to support early stage startups developing solutions at the intersection of life science, food and health.",
    "publishedAt": "2026-04-13T16:15:36.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-launches-aggie-venture-accelerator-advance-early-stage-life-science-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_1788_reduced.jpg?h=37bd9af6&itok=3XXTuw-j",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-aggie-square-partners-release-first-community-benefits-progress-report-highlighting-early",
    "campus": "davis",
    "title": "Aggie Square Partners Release First Community Benefits Progress Report Highlighting Early Impact",
    "summary": "The first Aggie Square Community Benefits Partnership Agreement (CBPA) Annual Progress Report has been released by UC Davis, the City of Sacramento and Wexford Science & Technology, documenting significant progress towards meeting many of the goals outlined in the CBPA.",
    "publishedAt": "2026-04-02T22:40:20.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/aggie-square-partners-release-first-community-benefits-progress-report-highlighting-early",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/MB20251001_AggieSq_IMG_6025.jpg?h=4997dc06&itok=8Y1gDdgI",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-mifti",
    "campus": "irvine",
    "title": "The $40 Trillion Question",
    "summary": "Can MIFTI, a scrappy UC Irvine-based startup, outpace billion-dollar fusion giants?",
    "publishedAt": "2026-03-30T22:53:07.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/mifti/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/03/MIFTI-1.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-health-ventures-appoints-troels-adrian-strengthen-industry-partnerships-and-advance",
    "campus": "davis",
    "title": "UC Davis Health Ventures Appoints Troels Adrian to Strengthen Industry Partnerships and Advance the UC Davis Health Clinical Test Bed",
    "summary": "UC Davis Health Ventures, part of the Innovation and Economic Development Office at UC Davis, today announced the appointment of Troels Adrian as Director of Industry Engagement.",
    "publishedAt": "2026-03-23T15:18:26.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-health-ventures-appoints-troels-adrian-strengthen-industry-partnerships-and-advance",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Troels%20Adrian%20COLOR.jpg?h=d73b4fec&itok=cVMoxhzz",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-food-health-angels-network-launches-accelerate-science-driven-food-and-health-innovation",
    "campus": "davis",
    "title": "Food & Health Angels Network Launches to Accelerate Science-Driven Food and Health Innovation",
    "summary": "Introducing the Food & Health Angels Network, a groundbreaking initiative launched to accelerate science-driven innovations in food and health, addressing the pressing issue of metabolic disease.",
    "publishedAt": "2026-03-19T16:15:08.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/food-health-angels-network-launches-accelerate-science-driven-food-and-health-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/real-food-pyramid-arrangement.jpg?h=5313cdcb&itok=vL82Pgy9",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-ucsf-receives-824m-nih-funding-driving-medical-breakthroughs",
    "campus": "sf",
    "title": "UCSF Receives $824M in NIH Funding, Driving Medical Breakthroughs",
    "summary": "UCSF Receives $824M in NIH Funding, Driving Medical Breakthroughs -",
    "publishedAt": "2026-03-13T07:00:00.000Z",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ucsf-receives-824m-nih-funding-driving-medical-breakthroughs",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-neuroqure",
    "campus": "irvine",
    "title": "A New Signal for Autism",
    "summary": "How UC Irvine research and a father’s story are changing the timeline of care",
    "publishedAt": "2026-02-27T20:40:15.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/neuroqure/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/02/NeuroQure-2.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-eira-bio",
    "campus": "irvine",
    "title": "Is This the Breakthrough Drug Development We’ve Been Waiting For?",
    "summary": "Eira Bio is targeting membrane proteins long considered unreachable by antibody drugs.",
    "publishedAt": "2026-02-17T18:32:41.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/eira-bio/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/02/Eira-Bio-1.png",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "irvine-innovation-uci-edu-vena-vitals",
    "campus": "irvine",
    "title": "Can Wearable Tech Finally Get Blood Pressure Right?",
    "summary": "Forget the cuff. Vena Vitals’ sticker-like sensor aims to deliver ICU-level data without ever breaking the skin.",
    "publishedAt": "2026-02-17T17:42:05.000Z",
    "sourceUrl": "https://innovation.uci.edu/news/vena-vitals/",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2026/02/Vena-Vitals-1.jpg",
    "sourceHost": "innovation.uci.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-highlights-translational-breakthroughs-and-startups-8th-annual-biotech-innovation",
    "campus": "davis",
    "title": "UC Davis Highlights Translational Breakthroughs and Startups at the 8th Annual Biotech Innovation Gallery",
    "summary": "UC Davis showcased groundbreaking translational research and innovative biotech startups at the 8th Annual Biotech Innovation Gallery in San Francisco. Hosted by the UC Davis Innovation and Economic Development Office, the event brought in over 330 attendees to connect with and explore potential partnerships with researchers and startup founders, aligning with the J.P. Morgan Healthcare Conference",
    "publishedAt": "2026-02-10T16:51:50.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-highlights-translational-breakthroughs-and-startups-8th-annual-biotech-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/David%20Segal_BIG.jpg?h=9c4c0580&itok=cZtQYKZp",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-announces-winners-autumn-2025-science-translation-and-innovative-research-grant",
    "campus": "davis",
    "title": "UC Davis Announces Winners of Autumn 2025 Science Translation and Innovative Research Grant Program",
    "summary": "The University of California, Davis, has awarded $100,000 through the autumn 2025 cohort of the Science Translation and Innovative Research (STAIR) Grant Program to help scientists advance innovative research with strong commercial potential.",
    "publishedAt": "2025-12-08T20:48:03.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-announces-winners-autumn-2025-science-translation-and-innovative-research-grant",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Baar_Abhaya.jpg?h=52d3fcb6&itok=7en2k7q-",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-venture-catalyst-fuels-record-year-uc-davis-innovation-startups",
    "campus": "davis",
    "title": "Venture Catalyst Fuels Record Year for UC Davis Innovation Startups",
    "summary": "At Venture Catalyst, part of the UC Davis Innovation and Economic Development Office, we're proud to support the translation of UC Davis research and technology into real-world applications by fostering the development of new ventures. Through strategic collaborations, training and mentorship programs, funding translational research, and proactive outreach, we foster the university’s entrepreneuri",
    "publishedAt": "2025-10-30T15:49:44.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/venture-catalyst-fuels-record-year-uc-davis-innovation-startups",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/VC%20Stats.png?h=c673cd1c&itok=x8MxJRRm",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-discovery-forum-highlights-how-uc-davis-center-glp-1-and-metabolic-health-innovation",
    "campus": "davis",
    "title": "Discovery Forum Highlights How UC Davis Is at the Center of GLP-1 and Metabolic Health Innovation",
    "summary": "The Discovery Forum showcased UC Davis as a leader in GLP-1 and metabolic health innovation, bringing together researchers, industry experts, and investors to explore how metabolic hormones are reshaping health and nutrition. With cutting-edge research, world-class facilities, and a strong innovation ecosystem, the event was a reminder of UC Davis’ unique ability to translate metabolic science int",
    "publishedAt": "2025-10-15T20:10:27.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/discovery-forum-highlights-how-uc-davis-center-glp-1-and-metabolic-health-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/IMG_5290.jpg?h=5dc9785f&itok=LuFfzZNo",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-healths-ifm-fund-backs-delix-therapeutics-first-investment",
    "campus": "davis",
    "title": "UC Davis Health’s IFM Fund Backs Delix Therapeutics in First Investment",
    "summary": "UC Davis Health Ventures, part of the Innovation and Economic Development Office (IEDO) at the University of California, Davis, today announced the first investment from its Investing in the Future of Medicine (IFM) Fund, backing Delix Therapeutics.",
    "publishedAt": "2025-10-02T16:10:43.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-healths-ifm-fund-backs-delix-therapeutics-first-investment",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/cameron_olson_lab_ccw.jpeg?h=c673cd1c&itok=akFyWePN",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-reflections-inaugural-triage-innovation-forum",
    "campus": "davis",
    "title": "Reflections on the Inaugural TRIage Innovation Forum",
    "summary": "Andrew Brown of UC Davis Health Ventures shares his thoughts on the creation and launch of the TRIage Innovation Forum—an engaging, rapid-pitch platform that helps researchers present their work in three minutes and receive tailored guidance, resources and connections to accelerate the translation of their innovations into real-world health solutions.",
    "publishedAt": "2025-09-02T16:23:28.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/reflections-inaugural-triage-innovation-forum",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/TRIage%20Pic%201.jpg?h=9c4c0580&itok=BsNJ9CMh",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-dough-data-how-graingeai-reimagining-ingredient-intelligence",
    "campus": "davis",
    "title": "From Dough to Data: How Grainge.ai is Reimagining Ingredient Intelligence",
    "summary": "Grainge.ai, a UC Davis–born startup, is transforming food manufacturing by using AI-driven ingredient intelligence to predict how grains, starches and other ingredients behave in formulations, helping companies innovate more efficiently and sustainably.",
    "publishedAt": "2025-08-18T21:19:43.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/dough-data-how-graingeai-reimagining-ingredient-intelligence",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/Screenshot%202025-08-18%20150316.png?h=1fdb4153&itok=kI5ywWph",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "davis-iedo-ucdavis-edu-uc-davis-sees-jump-records-invention-driven-health-innovation",
    "campus": "davis",
    "title": "UC Davis Sees Jump in Records of Invention, Driven by Health Innovation",
    "summary": "UC Davis saw a 34% increase in records of invention in FY 2025, driven largely by health-related innovations and first-time contributors, reflecting a growing culture of commercialization and cross-campus collaboration led by the Innovation and Economic Development Office.",
    "publishedAt": "2025-08-04T19:56:16.000Z",
    "sourceUrl": "https://iedo.ucdavis.edu/news/uc-davis-sees-jump-records-invention-driven-health-innovation",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_landscape_16x9/public/media/images/2025-05-22_Avantika%20Gokulnatha_resize.jpg?h=9855f42d&itok=2Wuomug3",
    "sourceHost": "iedo.ucdavis.edu"
  },
  {
    "id": "riverside-news-ucr-edu-tax-break-megadeals-spurred-innovation-communities",
    "campus": "riverside",
    "title": "Tax break ‘Megadeals’ spurred innovation in communities",
    "summary": "When cities, counties, or states provide corporations with big tax breaks to lure in factories, corporate headquarters, and other facilities, the economic benefits include more innovation outside the gates of the businesses lured into communities.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/08/25/tax-break-megadeals-spurred-innovation-communities",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-08/ex-960-tesla_gigafactory_1_-_december_2019-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-offering-islamic-bonds-expanded-corporate-financing-access",
    "campus": "riverside",
    "title": "Offering Islamic bonds expanded corporate financing access",
    "summary": "A study co-authored by UCR business professor Jean Helwege found that issuance of Islamic bonds attracted billions of dollars in new investment to Malaysia without undermining the country's market for conventional corporate bonds.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/08/04/offering-islamic-bonds-expanded-corporate-financing-access",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-08/960-gettyimages-1013052184.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-what-consumers-think-they-buy",
    "campus": "riverside",
    "title": "What consumers think before they buy",
    "summary": "Manufacturers have traditionally relied on sales figures to understand where they stand with consumers, but by the time those numbers arrive, the consumers’ buying decisions have already been made.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/06/23/what-consumers-think-they-buy",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-06/header2.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-uc-riverside-launches-online-mba-program",
    "campus": "riverside",
    "title": "UC Riverside launches online MBA program",
    "summary": "UC Riverside is launching a fully online Master of Business Administration program this fall, opening the door for students across California, the nation, and around the world to earn a University of California MBA degree remotely while continuing their careers and personal responsibilities.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/05/21/uc-riverside-launches-online-mba-program",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-05/biz-header-960.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-reclaiming-context-creative-works",
    "campus": "riverside",
    "title": "Reclaiming the context of creative works",
    "summary": "New research led by a UC Riverside professor has developed an AI tool that compensates for the shifting genre perceptions that impact how creative works are understood, evaluated, and even discovered.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/04/22/reclaiming-context-creative-works",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-04/960-gettyimages-2264305709-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-ucr-report-urges-broadband-be-state-utility",
    "campus": "riverside",
    "title": "UCR report urges broadband to be a state utility",
    "summary": "California should regulate broadband internet providers like public utilities — imposing rate controls, universal access requirements, and reliability standards to ensure every resident has affordable, high-speed internet access, according to a new UC Riverside public policy report.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/02/12/ucr-report-urges-broadband-be-state-utility",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-02/960-gettyimages-2231090399.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-tangos-sweet-legacy-lives",
    "campus": "riverside",
    "title": "Tango’s sweet legacy lives on",
    "summary": "The UCR-developed Tango mandarin has established itself as a symbol of innovation and sustainability in the global citrus market, generating more than $70 million in cumulative economic value for the university.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2026/01/15/tangos-sweet-legacy-lives",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2026-01/960-2025-11-05_tango_004.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-slower-company-acquisition-pace-can-boost-corporate-values",
    "campus": "riverside",
    "title": "Slower company acquisition pace can boost corporate values",
    "summary": "Expanding the time between company acquisitions improves the integration of the new assets and increases corporate values, study finds.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/12/08/slower-company-acquisition-pace-can-boost-corporate-values",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-12/960-gettyimages-147205360.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-shopping-two-stressful",
    "campus": "riverside",
    "title": "Shopping for two is stressful",
    "summary": "A study co-authored by a UCR business professor finds that shopping for goods or services that you will share is significantly more stressful than shopping for yourself or for something to be given to another person.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/12/02/shopping-two-stressful",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-12/960-stressed-shopper.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-study-finds-lower-emissions-higher-ethanol-gasoline",
    "campus": "riverside",
    "title": "Study finds lower emissions from higher-ethanol gasoline",
    "summary": "Landmark UC Riverside vehicle emissions study allows California to move forward with less costly and less polluting gasoline blend.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/11/25/study-finds-lower-emissions-higher-ethanol-gasoline",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-11/960-gettyimages-188115695-1_0.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-study-finds-moral-costs-over-pricing-essentials",
    "campus": "riverside",
    "title": "Study finds moral costs in over-pricing for essentials",
    "summary": "A study led by UC Riverside School of Business professor Margaret C. Campbell found that when companies hike prices on essentials like food, medicine, or medical devices, the financial rewards may be immediate—but the reputational damage may linger and ultimately cost more in the long run.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/11/03/study-finds-moral-costs-over-pricing-essentials",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-11/960-ex-gettyimages-1793165463-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-private-equity-takes-airports-new-heights",
    "campus": "riverside",
    "title": "Private equity takes airports to new heights",
    "summary": "Equity investors improved airport operating and customer service, finds a global study that spanned two decades and four continents.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/10/13/private-equity-takes-airports-new-heights",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-10/madrid-airport.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-farm-conservation-economical-path-save-river-water",
    "campus": "riverside",
    "title": "Farm conservation is an economical path to save river water",
    "summary": "The most cost-effective way to conserve the dwindling waters of the Colorado River may not come from building new reservoirs, canals, or wells, but from changing how water is used on farms that consume most of it.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/09/29/farm-conservation-economical-path-save-river-water",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-09/960-gettyimages-90285343.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-ucr-computer-scientists-boost-us-cybersecurity",
    "campus": "riverside",
    "title": "UCR computer scientists boost US cybersecurity",
    "summary": "UCR computer scientists are developing tools to expose hidden cybersecurity vulnerabilities, protect private data, and strengthen the digital defenses that safeguard everything from personal communications to national infrastructure.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/09/18/ucr-computer-scientists-boost-us-cybersecurity",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-09/960-gettyimages-2174551157.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-report-inland-empire-warehouse-workers-make-gains-through-collective-action",
    "campus": "riverside",
    "title": "Report: Inland Empire warehouse workers make gains through collective action",
    "summary": "In “State of the Unions: California Labor in 2024,” UCR researchers offer details on the growth, salaries, ethnicities, and ongoing struggles of warehouse workers in Riverside and San Bernardino counties",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/09/08/report-inland-empire-warehouse-workers-make-gains-through-collective-action",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2018-09/warehouse.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-nostalgia-asset-company-acquisitions",
    "campus": "riverside",
    "title": "Nostalgia is an asset in company acquisitions",
    "summary": "A study by UCR School of Business scholars found that nostalgia serves as a comforting and stabilizing force during company acquisition periods when employees feel vulnerable, fear losing their jobs, status, or advancement opportunities, and are thus inclined to send out résumés.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/08/20/nostalgia-asset-company-acquisitions",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-10/gettyimages-2238047024.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-groundwater-depletion-sinks-home-prices-californias-central-valley",
    "campus": "riverside",
    "title": "Groundwater depletion sinks home prices in California's Central Valley",
    "summary": "UC Riverside study has found that subsidence from excessive groundwater pumping in California's Central Valley reduced home values between 2.4% and 5.8% or between $6,689 and $16,165 per home. These costs totaled $1.87 billion in aggregate housing value lost, the study estimated.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/07/31/groundwater-depletion-sinks-home-prices-californias-central-valley",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-07/960-gettyimages-2208627482-copy.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-school-business-joins-council-global-business-schools",
    "campus": "riverside",
    "title": "School of Business joins council of global business schools",
    "summary": "UC Riverside’s School of Business has been accepted into the Graduate Management Admission Council, or GMAC, a prestigious global association of leading graduate business schools.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/07/17/school-business-joins-council-global-business-schools",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-07/960-2024-10-18_business_ribbon_cutting_139-copy_0_0.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "riverside-news-ucr-edu-uc-riverside-scholar-reimagines-student-engagement",
    "campus": "riverside",
    "title": "UC Riverside scholar reimagines student engagement",
    "summary": "The \"Carry the Class\" teaching method helps college students master concepts while fostering a sense of ownership through more meaningful social interactions among students and faculty, which creates a sense of community and shared purpose.",
    "publishedAt": "",
    "sourceUrl": "https://news.ucr.edu/articles/2025/07/07/uc-riverside-scholar-reimagines-student-engagement",
    "imageUrl": "https://news.ucr.edu/sites/default/files/2025-07/960-header-kyle-ingram.jpg",
    "sourceHost": "news.ucr.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-inventor-crispr-skeptical-about-ai",
    "campus": "sf",
    "title": "Inventor of Crispr is skeptical about AI",
    "summary": "The inventor of CRISPR is skeptical about AI’s impact on medical innovation",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/inventor-crispr-skeptical-about-ai",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-rare-disease-program-2026",
    "campus": "sf",
    "title": "Rare Disease Program 2026",
    "summary": "Rare Disease Program 2026",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/rare-disease-program-2026",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-ucsf-spinout-nets-91-m-test-virus-therapy-brain-cancer-china",
    "campus": "sf",
    "title": "UCSF spinout nets $9.1 M to test virus therapy for brain cancer in China",
    "summary": "UCSF spinout nets $9.1 M to test virus therapy for brain cancer in China",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/ucsf-spinout-nets-91-m-test-virus-therapy-brain-cancer-china",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-scientists-create-cancer-fighting-immune-cells-right-body",
    "campus": "sf",
    "title": "Scientists Create Cancer-Fighting Immune Cells Right in the Body",
    "summary": "Scientists Create Cancer-Fighting Immune Cells Right in the Body",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/scientists-create-cancer-fighting-immune-cells-right-body",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  },
  {
    "id": "sf-innovation-ucsf-edu-molecular-garbage-tumors-makes-easy-target-antibody-drugs",
    "campus": "sf",
    "title": "Molecular Garbage on Tumors Makes Easy Target for Antibody Drugs",
    "summary": "Cancer cells can ‘barf’ proteins onto their cell surface. That may create new targets for immunotherapies",
    "publishedAt": "",
    "sourceUrl": "https://innovation.ucsf.edu/media/news/molecular-garbage-tumors-makes-easy-target-antibody-drugs",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/themes/custom/innovation_v2/assets/images/social-default.jpg",
    "sourceHost": "innovation.ucsf.edu"
  }
];
