// AUTO-GENERATED by `vp run build-data`. Do not edit by hand.
// Run `vp run crawl` followed by `vp run build-data` to refresh.
import type { Program } from "./types";

export const CRAWLED_PROGRAMS: Program[] = [];
export const CRAWLED_AT: string | null = null;
