// AUTO-GENERATED by `vp run build-data`. Do not edit by hand.
// Source: data/crawled/*.json — last refresh: 2026-06-07T13:40:02.138Z
// Run `vp run crawl` followed by `vp run build-data` to refresh.
import type { Program } from "./types.ts";

export const CRAWLED_PROGRAMS: Program[] = [
  {
    "id": "davis-aggie-venture-accelerator",
    "slug": "aggie-venture-accelerator",
    "name": "Aggie Venture Accelerator",
    "campus": "davis",
    "type": "accelerator",
    "desc": "About Aggie Venture AcceleratorThe Aggie Venture Accelerator (AVA) is focused on backing early-stage life science startups solving complex problems at the interface of human, animal and planetary health.We back innovators confronting life’s most urgent challenges to bring a fuller, healthier and more resilient world within reach.",
    "longDescription": "The Aggie Venture Accelerator (AVA) is focused on supporting early-stage life science startups seeking to solve complex problems at the interface of human, animal and planetary health. We will back innovators confronting what we believe to be life’s most urgent challenges in an effort to bring a fuller, healthier and more resilient world within reach. Over the past decade UC Davis has supported the launch of 300+ startups that have collectively raised over $4B. AVA will give new founders an opportunity to join a community of investors, entrepreneurs, and industry representatives focused on mak",
    "industries": [
      "Health"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "June 20",
    "lastUpdated": "2026-06-03T03:03:08.682Z",
    "sourceUrl": "https://iedo.ucdavis.edu/aggie-venture-accelerator"
  },
  {
    "id": "davis-innovation-and-economic-development-office",
    "slug": "innovation-and-economic-development-office",
    "name": "Innovation and Economic Development Office",
    "campus": "davis",
    "type": "incubator",
    "desc": "UC Davis’ Innovation and Economic Development Office advances research and entrepreneurship by helping launch startups and accelerating technologies born in the lab.",
    "longDescription": "Are you a PhD student looking to turn breakthrough science into real-world health solutions? Located on UC Davis' Sacramento campus, Aggie Square is where the university, private industry and the community convene. Whether you want to take a tour of the buildings, host an event here for your team or organization or lease space, we'd love to see you at Aggie Square!",
    "industries": [
      "Health"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-03T03:03:06.281Z",
    "sourceUrl": "https://iedo.ucdavis.edu/",
    "imageUrl": "https://iedo.ucdavis.edu/sites/g/files/dgvnsk16861/files/styles/sf_hero_banner/public/media/images/Post%20TCO%20Final%20Photos%204%20%282%29.jpg?h=b7e2cbf2&itok=ZFYRAVtp"
  },
  {
    "id": "irvine-funding-resources-uci-beall-applied-innovation",
    "slug": "funding-resources-uci-beall-applied-innovation",
    "name": "Funding Resources – UCI Beall Applied Innovation",
    "campus": "irvine",
    "type": "funding",
    "desc": "Proof of Product (POP) Grants is a program that awards funding to researchers to accelerate the development of UCI’s commercially promising technology. Real-world, hands-on learning that involves finding customers and…",
    "longDescription": "Proof of Product (POP) Grants is a program that awards funding to researchers to accelerate the development of UCI’s commercially promising technology. Real-world, hands-on learning that involves finding customers and understanding their problems to achieve a product/market fit. We work with an extensive network of angel and venture capital investors to provide deal flow opportunities and connection to startups and entrepreneurs from campus and the Orange County community. Small Business Innovative Research (SBIR) and Small business Technology Transfer (STTR) are competitive programs that awar",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:26.417Z",
    "sourceUrl": "https://innovation.uci.edu/funding-resources",
    "imageUrl": "https://innovation.uci.edu/wp-content/uploads/2022/01/Janelle-King-Student-Startup-Fund-UCI.png"
  },
  {
    "id": "irvine-pop-grants-uci-beall-applied-innovation",
    "slug": "pop-grants-uci-beall-applied-innovation",
    "name": "POP Grants – UCI Beall Applied Innovation",
    "campus": "irvine",
    "type": "incubator",
    "desc": "Makani Science Has Created the Most Important Medical Device You’ll Never Notice Bill Tomlinson’s AI doesn’t just chat. It remembers, it cares, and it might just help us save ourselves. Tibor Juhasz has been perfectin…",
    "longDescription": "Makani Science Has Created the Most Important Medical Device You’ll Never Notice Bill Tomlinson’s AI doesn’t just chat. It remembers, it cares, and it might just help us save ourselves. Tibor Juhasz has been perfecting a laser treatment for glaucoma NeoCare Innovations Technology Offers a Safer Start for Vulnerable Newborns",
    "industries": [
      "AI / ML"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:17.830Z",
    "sourceUrl": "https://innovation.uci.edu/pop-grants/"
  },
  {
    "id": "la-center-for-healthcare-innovation",
    "slug": "center-for-healthcare-innovation",
    "name": "Center for Healthcare Innovation",
    "campus": "la",
    "type": "incubator",
    "desc": "“The future of healthcare will be shaped by bold collaboration. At the Center, we bring together industry leaders, faculty researchers, entrepreneurs, and the next generation of student leaders to translate ideas into impact. Together, we are pioneering innovative solutions that address healthcare’s most urgent challenges.”",
    "longDescription": "“The future of healthcare will be shaped by bold collaboration. At the Center, we bring together industry leaders, faculty researchers, entrepreneurs, and the next generation of student leaders to translate ideas into impact. Together, we are pioneering innovative solutions that address healthcare’s most urgent challenges.” — Jodie Lesh (’92) Executive Director, Center for Healthcare Innovation “With Anderson’s world-class faculty, innovative curriculum, and student-led initiatives, the Center is poised to become a premier hub for transformative learning—where bold ideas and cutting-edge resea",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:10.875Z",
    "sourceUrl": "https://www.anderson.ucla.edu/about/centers/center-for-healthcare-innovation",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/banner_desktop/public/image/2025-11/2025-healthcare-hero-home.jpg?itok=AsXoRokf"
  },
  {
    "id": "la-early-stage-investment-fund",
    "slug": "early-stage-investment-fund",
    "name": "Early-Stage Investment Fund",
    "campus": "la",
    "type": "funding",
    "desc": "The UCLA Early-Stage Investment Fund seeks promising pre-seed ventures for investment. Led by a cohort of 15 to 25 UCLA MBA candidates, the Fund sources, evaluates and recommends one or two annual investments to the UCLA Endowment. Selected ventures will typically receive investment via a $50,000 convertible note agreement.",
    "longDescription": "The UCLA Early-Stage Investment Fund seeks promising pre-seed ventures for investment. Led by a cohort of 15 to 25 UCLA MBA candidates, the Fund sources, evaluates and recommends one or two annual investments to the UCLA Endowment. Selected ventures will typically receive investment via a $50,000 convertible note agreement. The Fund invests in startups with strong teams, innovative ideas and long-term growth potential. The Fund's investment strategy, while industry agnostic, places a significant emphasis on pre-seed startups that exhibit a credible trajectory toward Series A fundraising. The U",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:28.382Z",
    "sourceUrl": "https://www.anderson.ucla.edu/for-companies/early-stage-investment-fund"
  },
  {
    "id": "la-information-systems-research-program",
    "slug": "information-systems-research-program",
    "name": "Information Systems Research Program",
    "campus": "la",
    "type": "incubator",
    "desc": "The ISRP today supports a variety of research and professional activities. It funds ongoing faculty research projects. It provides for research assistantships and needed equipment, and supports organized workshops such as WISRD and travel to scholarly conferences. It also supports the Visiting Fellows Program. It maintains relationships with business firms that cooperate in and serve as sites for research. A few participate in cooperative research as IS Research Associates.",
    "longDescription": "The ISRP today supports a variety of research and professional activities. It funds ongoing faculty research projects. It provides for research assistantships and needed equipment, and supports organized workshops such as WISRD and travel to scholarly conferences. It also supports the Visiting Fellows Program. It maintains relationships with business firms that cooperate in and serve as sites for research. A few participate in cooperative research as IS Research Associates. Following a recently held WISRD that identified the need to bring researchers from multiple scholarly backgrounds togethe",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:25.287Z",
    "sourceUrl": "https://www.anderson.ucla.edu/faculty-and-research/information-systems-research-program",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/banner_desktop/public/images/2017/sites/programs/hero-h440-tpl.jpg?itok=XIKD0kkK"
  },
  {
    "id": "la-management-development-for-entrepreneurs",
    "slug": "management-development-for-entrepreneurs",
    "name": "Management Development for Entrepreneurs",
    "campus": "la",
    "type": "certificate",
    "desc": "The Management Development for Entrepreneurs (MDE) program supplements entrepreneurial vision with entrepreneurial competence. The 10-day certificate program is offered on the main UCLA campus each fall. The MDE program will provide business owners and executives with a road map and the tools to make the necessary pivots to survive and grow in a pandemic economy.",
    "longDescription": "The Management Development for Entrepreneurs (MDE) program supplements entrepreneurial vision with entrepreneurial competence. The 10-day certificate program is offered on the main UCLA campus each fall. The MDE program will provide business owners and executives with a road map and the tools to make the necessary pivots to survive and grow in a pandemic economy. Banks as Credit Facilities Non-Bank Sources of Credit Small Business Administration Total Quality Management Process Analysis Supply Chain Management Developing a Marketing Niche Organizational Design and Change Competitive Strengths",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:45.767Z",
    "sourceUrl": "https://www.anderson.ucla.edu/about/centers/price-center-for-entrepreneurship-and-innovation/for-professionals/management-development-for-entrepreneurs",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/banner_desktop/public/images/2017/sites/centers/price/2020/Professionals/PRICE-MDE-online-banner.jpg?itok=KMURY2Ij"
  },
  {
    "id": "la-price-center-for-entrepreneurship-and-innovation-fellowships",
    "slug": "price-center-for-entrepreneurship-and-innovation-fellowships",
    "name": "Price Center for Entrepreneurship and Innovation - Fellowships",
    "campus": "la",
    "type": "incubator",
    "desc": "The Deutschman Venture Fellows Program provides MBA students with hands-on venture capital management and investment training, and/or operating company experience. Fellows are placed with sponsoring venture capital firms or portfolio companies for three-month summer internships. Financial support is provided by a stipend from the Deutschman Venture Fellows endowment and a monthly salary from the participating firm.",
    "longDescription": "The Deutschman Venture Fellows Program provides MBA students with hands-on venture capital management and investment training, and/or operating company experience. Fellows are placed with sponsoring venture capital firms or portfolio companies for three-month summer internships. Financial support is provided by a stipend from the Deutschman Venture Fellows endowment and a monthly salary from the participating firm. The relationship between sponsoring organizations and Deutschman Venture Fellows is mutually productive. Fellows placed in a venture capital firm engage in various aspects of portfo",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:34.385Z",
    "sourceUrl": "https://www.anderson.ucla.edu/about/centers/price-center-for-entrepreneurship-and-innovation/for-students/fellowships",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/banner_desktop/public/images/2017/sites/centers/price/2020/price-center-fellowships.jpg?itok=xvB_LKBR"
  },
  {
    "id": "la-student-investment-fund",
    "slug": "student-investment-fund",
    "name": "Student Investment Fund",
    "campus": "la",
    "type": "funding",
    "desc": "The SIF is a prestigious element of the Anderson experience that exposes students to situations they would encounter in a typical investment management firm. For the first six months, SIF Fellows collectively manage the fund. The equity portion is then divided equally among the Fellows and managed individually for the remaining six months. The fixed-income portfolio is managed as a group for the entire period. The Fellows visit at least 25 investment managers to learn about different investment philosophies and styles, as well as at least five current or prospective portfolio companies to conduct in-depth due diligence.",
    "longDescription": "The SIF is a prestigious element of the Anderson experience that exposes students to situations they would encounter in a typical investment management firm. For the first six months, SIF Fellows collectively manage the fund. The equity portion is then divided equally among the Fellows and managed individually for the remaining six months. The fixed-income portfolio is managed as a group for the entire period. The Fellows visit at least 25 investment managers to learn about different investment philosophies and styles, as well as at least five current or prospective portfolio companies to cond",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:36.121Z",
    "sourceUrl": "https://www.anderson.ucla.edu/about/centers/price-center-for-entrepreneurship-and-innovation/for-students/student-investment-fund",
    "imageUrl": "https://www.anderson.ucla.edu/sites/default/files/styles/banner_desktop/public/images/2017/sites/clubs/STUDENT-anderson-banner.jpg?itok=j-jnQsJS"
  },
  {
    "id": "la-ucla-anderson-venture-accelerator",
    "slug": "ucla-anderson-venture-accelerator",
    "name": "UCLA Anderson Venture Accelerator",
    "campus": "la",
    "type": "accelerator",
    "desc": "The Venture Accelerator at UCLA Anderson, housed within the Harold and Pauline Price Center for Entrepreneurship & Innovation, is a transformative cohort-based program for early-stage startups and their founders.",
    "longDescription": "Confirmed registrants will receive detailed information on location and logistics.",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://www.anderson.ucla.edu/apply",
    "lastUpdated": "2026-06-07T13:39:22.007Z",
    "sourceUrl": "https://www.anderson.ucla.edu/about/centers/price-center-for-entrepreneurship-and-innovation/anderson-venture-accelerator"
  },
  {
    "id": "merced-fall-2023-climate-action-innovation-and-entrepreneurship-proof-of-concept-funds",
    "slug": "fall-2023-climate-action-innovation-and-entrepreneurship-proof-of-concept-funds",
    "name": "Fall 2023 Climate Action Innovation and Entrepreneurship Proof of Concept Funds",
    "campus": "merced",
    "type": "funding",
    "desc": "The UC Merced Fall 2023 Climate Action Innovation and Entrepreneurship Proof of Concept Funds solicitation opened in August 2023. Seven proposals were received, requesting a total of $349,169. These were of high quality and underwent two rounds of comprehensive review. ORED awarded five projects (listed below) for a total of $249,474. These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy.",
    "longDescription": "The UC Merced Fall 2023 Climate Action Innovation and Entrepreneurship Proof of Concept Funds solicitation opened in August 2023. Seven proposals were received, requesting a total of $349,169. These were of high quality and underwent two rounds of comprehensive review. ORED awarded five projects (listed below) for a total of $249,474. These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy. Commercializing novel thermal storage systems for electrification of industrial steam systems Bench-Stable Nickel (0) C",
    "industries": [
      "Climate",
      "Energy"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:58.123Z",
    "sourceUrl": "https://research.ucmerced.edu/state-climate-funds/fall-2023-climate-action-innovation-and-entrepreneurship-proof-concept-funds"
  },
  {
    "id": "merced-fall-2023-climate-action-seed-funds",
    "slug": "fall-2023-climate-action-seed-funds",
    "name": "Fall 2023 Climate Action Seed Funds",
    "campus": "merced",
    "type": "incubator",
    "desc": "The Fall 2023 Climate Action Seed Funds solicitation was issued in June 2023. Twenty-five proposals were received, requesting a total of $11,785,877. These were of high quality and underwent two rounds of comprehensive review. ORED awarded eleven, two small (up to $100K) and nine large (up to $1M), projects (listed below) for a total of $4,889,426 These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy.",
    "longDescription": "The Fall 2023 Climate Action Seed Funds solicitation was issued in June 2023. Twenty-five proposals were received, requesting a total of $11,785,877. These were of high quality and underwent two rounds of comprehensive review. ORED awarded eleven, two small (up to $100K) and nine large (up to $1M), projects (listed below) for a total of $4,889,426 These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy. Biotech for Biodiversity (B4B): Rapid Delivery of Community-Scale Diversity Data for Genomic Restoration D",
    "industries": [
      "Biotech",
      "Climate"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:56.248Z",
    "sourceUrl": "https://research.ucmerced.edu/state-climate-funds/fall-2023-climate-action-seed-funds"
  },
  {
    "id": "merced-regenerative-agriculture-initiatives-accelerators-incubators-entrepreneurship-centers-and-sbdcs",
    "slug": "regenerative-agriculture-initiatives-accelerators-incubators-entrepreneurship-centers-and-sbdcs",
    "name": "Regenerative Agriculture Initiatives - Accelerators, Incubators, Entrepreneurship Centers, and SBDCs",
    "campus": "merced",
    "type": "incubator",
    "desc": "University of California Merced Office of Research and Economic Development Request for Expressions of Interest",
    "longDescription": "University of California Merced Office of Research and Economic Development Request for Expressions of Interest in Accelerators, Incubators, Entrepreneurship Centers, and Small Business Development Centers for Regenerative Agriculture Initiatives I. Overview The University of California Merced Office of Research and Economic Development (UCM ORED) is seeking expressions of interest from accelerators, incubators, entrepreneurship centers, and small business development centers to partner on regenerative agriculture initiatives. This call aims to identify potential partners who can provide suppo",
    "industries": [
      "AgTech"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:48.019Z",
    "sourceUrl": "https://research.ucmerced.edu/form/regenerative-agriculture-initiatives-accelerators-incubators-entrepreneurship-centers-and-sbdcs"
  },
  {
    "id": "merced-research-sustainability-fund",
    "slug": "research-sustainability-fund",
    "name": "Research Sustainability Fund",
    "campus": "merced",
    "type": "funding",
    "desc": "On June 5, 2025, Chancellor Muñoz committed $1.5 million in campus funds to support faculty researchers who have been impacted by a pause or stoppage in federal grant award funding. This fund is intended to be used over the coming 12-24 months to support faculty researchers as the federal funding landscape continues to be volatile. Unfortunately, depending on the magnitude of federal actions, it is possible that the fund will not meet all needs. The Research Sustainability Fund will address a researcher’s temporary, short-term operational needs to facilitate transition or ramp-down costs resulting from changes in federal funding.",
    "longDescription": "On June 5, 2025, Chancellor Muñoz committed $1.5 million in campus funds to support faculty researchers who have been impacted by a pause or stoppage in federal grant award funding. This fund is intended to be used over the coming 12-24 months to support faculty researchers as the federal funding landscape continues to be volatile. Unfortunately, depending on the magnitude of federal actions, it is possible that the fund will not meet all needs. The Research Sustainability Fund will address a researcher’s temporary, short-term operational needs to facilitate transition or ramp-down costs resul",
    "industries": [
      "Climate"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:40:01.979Z",
    "sourceUrl": "https://research.ucmerced.edu/research-sustainability-fund"
  },
  {
    "id": "merced-spring-2023-climate-action-seed-funds",
    "slug": "spring-2023-climate-action-seed-funds",
    "name": "Spring 2023 Climate Action Seed Funds",
    "campus": "merced",
    "type": "incubator",
    "desc": "The Spring 2023 Climate Action Seed Funds solicitation was issued in January 2023. Twenty-three proposals were received, requesting a total of $12,925,522. These were of high quality and underwent two rounds of comprehensive review. ORED awarded nine, three small (up to $50K) and six large (up to $1M), projects (listed below) for a total of $4,096,197. These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy.",
    "longDescription": "The Spring 2023 Climate Action Seed Funds solicitation was issued in January 2023. Twenty-three proposals were received, requesting a total of $12,925,522. These were of high quality and underwent two rounds of comprehensive review. ORED awarded nine, three small (up to $50K) and six large (up to $1M), projects (listed below) for a total of $4,096,197. These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy. Electrochemical drinking water treatment for climate adaptation The research addresses the specific C",
    "industries": [
      "Climate"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:54.126Z",
    "sourceUrl": "https://research.ucmerced.edu/state-climate-funds/spring-2023-climate-action-seed-funds"
  },
  {
    "id": "merced-spring-2024-climate-action-innovation-and-entrepreneurship-proof-of-concept-funds",
    "slug": "spring-2024-climate-action-innovation-and-entrepreneurship-proof-of-concept-funds",
    "name": "Spring 2024 Climate Action Innovation and Entrepreneurship Proof of Concept Funds",
    "campus": "merced",
    "type": "funding",
    "desc": "The Spring 2024 UC Merced Climate Action Innovation and Entrepreneurship Proof of Concept Funds solicitation opened in February 2024. Ten proposals were received, requesting ~$500,000. These were of high quality and underwent two rounds of comprehensive review. ORED awarded five projects (listed below) for a total of $249,765. These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy.",
    "longDescription": "The Spring 2024 UC Merced Climate Action Innovation and Entrepreneurship Proof of Concept Funds solicitation opened in February 2024. Ten proposals were received, requesting ~$500,000. These were of high quality and underwent two rounds of comprehensive review. ORED awarded five projects (listed below) for a total of $249,765. These projects are synergistic with the State of California’s climate action priorities outlined in the California Climate Adaptation Strategy.",
    "industries": [
      "Climate"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:40:00.052Z",
    "sourceUrl": "https://research.ucmerced.edu/state-climate-funds/spring-2024-climate-action-innovation-and-entrepreneurship-proof-concept-funds"
  },
  {
    "id": "merced-state-climate-funds",
    "slug": "state-climate-funds",
    "name": "State Climate Funds",
    "campus": "merced",
    "type": "competition",
    "desc": "The State of California designated $18 million to the University of California (UC) Merced, per AB 179, for climate action research and innovation to address critical needs of the state. The Office of Research, Innovation & Economic Development was designated to administer these funds. A total of $9M in Climate Action Research Seed Funds will be made available through two peer-reviewed rounds of competition. The focus for these funds is on applied research and development projects that will build capacity for climate resilience, adaptation, and mitigation across the State of California. In keeping with UC Merced’s commitment to community and to serving the state’s diverse population, awarded projects explicitly consider the disparate impact of climate change/action on vulnerable communities and incorporate the perspectives of partners/investigators from diverse disciplines, backgrounds, genders, race/ethnicities, and lived experiences.",
    "longDescription": "The State of California designated $18 million to the University of California (UC) Merced, per AB 179, for climate action research and innovation to address critical needs of the state. The Office of Research, Innovation & Economic Development was designated to administer these funds. A total of $9M in Climate Action Research Seed Funds will be made available through two peer-reviewed rounds of competition. The focus for these funds is on applied research and development projects that will build capacity for climate resilience, adaptation, and mitigation across the State of California. In kee",
    "industries": [
      "Climate"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:52.222Z",
    "sourceUrl": "https://research.ucmerced.edu/state-climate-funds"
  },
  {
    "id": "santabarbara-prototyping-lab-space",
    "slug": "prototyping-lab-space",
    "name": "Prototyping + Lab Space",
    "campus": "santabarbara",
    "type": "maker",
    "desc": "The CNSI Innovation Workshop – a makerspace facility – is now open in Elings Hall, envisioned as a resource to both local startups as well as the campus community. The Innovation Workshop enables innovators from UCSB…",
    "longDescription": "The CNSI Innovation Workshop – a makerspace facility – is now open in Elings Hall, envisioned as a resource to both local startups as well as the campus community. The Innovation Workshop enables innovators from UCSB and local companies to build and test prototypes their inventions. As not all ideas work, nor are all workable ideas practical or have the desired impact in solving important problems, the best way to develop ideas into impactful innovations is build, test, and persistently improve them. Thus the goal of the CNSI Innovation Workshop is to be a resource to address this stage of bus",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:09.727Z",
    "sourceUrl": "https://innovation.ucsb.edu/prototyping-lab-space",
    "imageUrl": "https://innovation.ucsb.edu/sites/default/files/images/blog/2020-08/Innovation_Workshop_Lab_004.jpg"
  },
  {
    "id": "santacruz-innovation-catalyst-proof-of-concept-program",
    "slug": "innovation-catalyst-proof-of-concept-program",
    "name": "Innovation Catalyst Proof-Of-Concept Program",
    "campus": "santacruz",
    "type": "funding",
    "desc": "Innovation Catalyst is a proof-of-concept program managed by the Innovation & Business Engagement Hub, focused on providing targeted gap funding, training, mentorship, and support to UC Santa Cruz researchers in order to help de-risk and/or validate the implementation, adoption, and commercialization potential of early-stage technology innovations.",
    "longDescription": "Innovation Catalyst is a proof-of-concept program managed by the Innovation & Business Engagement Hub, focused on providing targeted gap funding, training, mentorship, and support to UC Santa Cruz researchers in order to help de-risk and/or validate the implementation, adoption, and commercialization potential of early-stage technology innovations. The overall objective of the program is to better position innovations to move out of the University, (e.g., attract the interest of entrepreneurs, companies, and investors for licensing), and catalyze the process leading to transformative change an",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:27.788Z",
    "sourceUrl": "https://innovation.ucsc.edu/faculty-researchers/innovation-catalyst-grant/"
  },
  {
    "id": "santacruz-nsf-i-corps-program",
    "slug": "nsf-i-corps-program",
    "name": "NSF I-Corps Program",
    "campus": "santacruz",
    "type": "incubator",
    "desc": "The Innovation & Business Engagement Hub organizes immersive lean launchpad workshops series focused on training teams advancing university innovations or working on translational and use-inspired research projects. These series provide valuable training on identifying pathways for adoption and implementation and finding a scalable business model through the customer discovery process.",
    "longDescription": "The Innovation & Business Engagement Hub organizes immersive lean launchpad workshops series focused on training teams advancing university innovations or working on translational and use-inspired research projects. These series provide valuable training on identifying pathways for adoption and implementation and finding a scalable business model through the customer discovery process. UC Santa Cruz is a partner institution in the (I-Corps) Hub for the Northwest Region and will be providing these series on the Central Coast. These evening sessions teach you to identify your top customer segmen",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "applicationLink": "https://airtable.com/appchtuZSEDR2xXod/pagM3WEdQVbm6uSlV/form?prefill_Cohort=recsiWzp1iPM2Xpdp",
    "lastUpdated": "2026-06-07T13:39:35.272Z",
    "sourceUrl": "https://innovation.ucsc.edu/entrepreneurs-innovators/lean-launchpad-workshop/"
  },
  {
    "id": "santacruz-research-infrastructure-commons-ric-program",
    "slug": "research-infrastructure-commons-ric-program",
    "name": "Research Infrastructure Commons (RIC) Program",
    "campus": "santacruz",
    "type": "incubator",
    "desc": "The Research Infrastructure Commons (RIC) program consists of a group of research facilities and other resources that have made available routine services to industry users for commercial purposes under commercial rate structures and business-friendly terms.",
    "longDescription": "The Research Infrastructure Commons (RIC) program consists of a group of research facilities and other resources that have made available routine services to industry users for commercial purposes under commercial rate structures and business-friendly terms. Core Manager Name: Beverley RabbittsCore Manager Email: brabbitt@ucsc.eduRRID Number: SCR_021114RIC Services: library formatting, cytological profiling, biochemical assays, imaging assays and high-content screening, and skill training. Core Manager Name: Vitor Hugo Balasco SerrãoCore Manager Email: vbalasco@ucsc.eduRRID number: SCR_021755R",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:24.106Z",
    "sourceUrl": "https://innovation.ucsc.edu/industry-corporate-partners/research-infrastructure-commons-ric-program/"
  },
  {
    "id": "sd-explore-our-startup-toolkit",
    "slug": "explore-our-startup-toolkit",
    "name": "Explore Our Startup Toolkit",
    "campus": "sd",
    "type": "funding",
    "desc": "UC San Diego works with a number of service providers to help you with the building blocks of starting a new company- incorporation services, IP management, accounting services, grant writing and more. Find the service that is right for you. We have also provided a number of educational resources on these topics.",
    "longDescription": "UC San Diego works with a number of service providers to help you with the building blocks of starting a new company- incorporation services, IP management, accounting services, grant writing and more. Find the service that is right for you. We have also provided a number of educational resources on these topics. Secure the backing you need to succeed. Our office is dedicated to providing budding companies with internal funding opportunities and access to external investors.",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:12.325Z",
    "sourceUrl": "https://innovation.ucsd.edu/startup/startup-toolkit/index.html"
  },
  {
    "id": "sf-catalyst-program",
    "slug": "catalyst-program",
    "name": "Catalyst Program",
    "campus": "sf",
    "type": "funding",
    "desc": "Catalyst Program accelerates UCSF innovations by providing expert guidance, industry connections, and funding to advance promising discoveries.",
    "longDescription": "The Catalyst Program is UCSF’s translational accelerator focused on advancing UCSF discoveries for patient benefit and commercialization. The Catalyst Program advances translational research and provides entrepreneurship education for UCSF Innovators (Faculty, Students, Trainees). Catalyst Awards provide UCSF researchers mentorship and seed funding to advance therapeutics, diagnostics, medical devices, and digital health. Kunal Patel UCSF Innovation Fund in support of the Catalyst Program Offers hands-on experience in translational research, commercialization, & industry-academic collaboration",
    "industries": [
      "Biotech",
      "Health"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:48.404Z",
    "sourceUrl": "https://innovation.ucsf.edu/services/innovation-entrepreneurship/funding-translational/catalyst-program",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/files/2024-12/page-hero-5.jpg"
  },
  {
    "id": "sf-engagement-opportunity-development",
    "slug": "engagement-opportunity-development",
    "name": "Engagement & Opportunity Development",
    "campus": "sf",
    "type": "funding",
    "desc": "Our team partners with faculty to turn cutting-edge research into market-ready innovations, connecting ideas to funding and advancing healthcare solutions.",
    "longDescription": "Our Engagement and Opportunity Development Team collaborates with faculty to shape business opportunities around cutting-edge technologies. Taking a market-first approach, we identify product potential based on research discoveries, tailoring business models for optimal market entry. We focus on advancing innovations ready for business while providing the necessary support. Our streamlined process connects researchers to funding sources and, when needed, assists in launching new businesses. With a dedicated focus on assessing UCSF research for market potential, we ensure greater access to tran",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:43.056Z",
    "sourceUrl": "https://innovation.ucsf.edu/services/healthtech-commercialization/engagement-and-opportunity-development",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/files/2024-12/page-hero-10.jpg"
  },
  {
    "id": "sf-entrepreneurship-resources",
    "slug": "entrepreneurship-resources",
    "name": "Entrepreneurship Resources",
    "campus": "sf",
    "type": "funding",
    "desc": "Innovation Ventures’ Startup Resources aggregates tools, programs, accelerators, legal, funding &amp; FDA info to help founders launch startups.",
    "longDescription": "The Entrepreneurship program can direct you to the information and resources you need to start a company. We have aggregated websites and information on key topics that relate to entrepreneurship.",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:49.708Z",
    "sourceUrl": "https://innovation.ucsf.edu/resources/startup-resources",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/files/2024-12/Newsletter-Page.jpg"
  },
  {
    "id": "sf-panther-program",
    "slug": "panther-program",
    "name": "PANTher Program",
    "campus": "sf",
    "type": "incubator",
    "desc": "Advancing pediatric neurotherapeutics through research, collaboration, and clinical trials for rare childhood neurological diseases.",
    "longDescription": "The Pediatric Advanced Neurotherapeutics (PANTher) Program was developed to coordinate basic science, translational and clinical research efforts relevant to the treatment of childhood neurological diseases. We are particularly interested in treatments for rare diseases, including gene therapy and medications with novel therapeutic mechanisms. Its goals are to:",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:58.500Z",
    "sourceUrl": "https://innovation.ucsf.edu/partnerships/panther-program",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/files/2025-01/page-hero-3.jpg"
  },
  {
    "id": "sf-strategic-alliances",
    "slug": "strategic-alliances",
    "name": "Strategic Alliances",
    "campus": "sf",
    "type": "funding",
    "desc": "Strategic Alliances fosters collaboration, connecting researchers with partners for funding, commercialization, &amp; alliance management.",
    "longDescription": "The Office of Strategic Alliances develops and manages UCSF's largest industry partnerships. It is our goal to identify mutually beneficial collaborations between UCSF and strategic partners, often with the objective of providing research funding for projects at UCSF. We leverage our extensive internal and external networks to connect collaborators to our researchers and clinicians, and once a partnership is established we provide alliance support to ensure a successful relationship. Discover how you can thrive through strategic alliances, joint ventures, & mutually beneficial collaborations.",
    "industries": [],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:45.776Z",
    "sourceUrl": "https://innovation.ucsf.edu/services/healthtech-commercialization/strategic-alliances",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/files/2024-09/Strategic%20Alliences%20Banner.jpg"
  },
  {
    "id": "sf-translational-funding",
    "slug": "translational-funding",
    "name": "Translational Funding",
    "campus": "sf",
    "type": "funding",
    "desc": "UCSF can help ensure that the next generation of medical breakthroughs are developed and that everyone has access to the care they need.",
    "longDescription": "Translational science is essential to the future of medicine. New ideas need to be developed and validated. Funding health-focused science at UCSF is the key to translating our discoveries into new treatments and cures for diseases. By funding translational science, UCSF can help ensure that the next generation of medical breakthroughs is developed and that everyone has access to the care they need. The Catalyst Program is UCSF’s translational accelerator focused on advancing UCSF discoveries for patient benefit and commercialization. The Catalyst Program advances translational research and pr",
    "industries": [
      "Health"
    ],
    "stage": "Idea",
    "eligibility": [
      "Open to public"
    ],
    "duration": "Not specified",
    "funding": "Not disclosed",
    "selectivity": "Not disclosed",
    "cohortSize": null,
    "deadline": "See program site",
    "lastUpdated": "2026-06-07T13:39:41.667Z",
    "sourceUrl": "https://innovation.ucsf.edu/services/innovation-entrepreneurship/funding-translational",
    "imageUrl": "https://innovation.ucsf.edu/sites/innovation.ucsf.edu/files/2024-12/example-rotator-4_0.jpg"
  }
];

export const CRAWLED_AT: string | null = "2026-06-07T13:40:02.138Z";
